Wild Life: error.c File Reference
error.c File Reference
error messaging, etc.
Functions
static long depth_gs ()
depth_gs
static long depth_cs ()
depth_cs
static long depth_ts ()
depth_ts
void stack_info (FILE *outfile)
stack_info
void outputline (char *format,...)
void outputline(char *format,...)
void traceline (char *format,...)
traceline
void infoline (char *format,...)
infoline
void warningline (char *format,...)
warningline
void Errorline (char *format,...)
Errorline.
void Syntaxerrorline (char *format,...)
Syntaxerrorline.
void init_trace ()
init_trace
void reset_step ()
reset_step
void tracing ()
tracing
void new_trace (long newtrace)
new_trace
void new_step (long newstep)
new_step
void set_trace_to_prove ()
set_trace_to_prove
void toggle_trace ()
toggle_trace
void toggle_step ()
toggle_step
void perr (char *str)
perr
void perr_s (char *s1, char *s2)
perr_s
void perr_s2 (char *s1, char *s2, char *s3)
perr_s2
void perr_i (char *str, long i)
perr_i
long warning ()
warning
long warningx ()
warningx
void report_error_main (ptr_psi_term g, char *s, char *s2)
report_error_main
void report_error (ptr_psi_term g, char *s)
report_error
long reportAndAbort (ptr_psi_term g, char *s)
reportAndAbort
void report_warning (ptr_psi_term g, char *s)
report_warning
void report_error2_main (ptr_psi_term g, char *s, char *s2)
report_error2_main
void report_error2 (ptr_psi_term g, char *s)
report_error2
void report_warning2 (ptr_psi_term g, char *s)
report_warning2
void nonnum_warning (ptr_psi_term t, ptr_psi_term arg1, ptr_psi_term arg2)
nonnum_warning
long nonint_warning (ptr_psi_term arg, REAL val, char *msg)
nonint_warning
long bit_and_warning (ptr_psi_term arg, REAL val)
bit_and_warning
long bit_or_warning (ptr_psi_term arg, REAL val)
bit_or_warning
long bit_not_warning (ptr_psi_term arg, REAL val)
bit_not_warning
long int_div_warning (ptr_psi_term arg, REAL val)
int_div_warning
long mod_warning (ptr_psi_term arg, REAL val, int zero)
mod_warning
long shift_warning (long dir, ptr_psi_term arg, REAL val)
shift_warning
Variables
long warningflag =TRUE
long quietflag =FALSE
long trace =FALSE
long verbose =FALSE
long stepflag = 0
long steptrace = 0
long stepcount = 0
Detailed Description
error messaging, etc.
Definition in file error.c.
Function Documentation
long bit_and_warning (ptr_psi_term arg, REAL val)
bit_and_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
Definition at line 992 of file error.c.
References nonint_warning().
 {
   return nonint_warning(arg,val,"of bitwise 'and' operation is not an integer");
 }
long bit_not_warning (ptr_psi_term arg, REAL val)
bit_not_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
Definition at line 1016 of file error.c.
References nonint_warning().
 {
   return nonint_warning(arg,val,"of bitwise 'not' operation is not an integer");
 }
long bit_or_warning (ptr_psi_term arg, REAL val)
bit_or_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
Definition at line 1004 of file error.c.
References nonint_warning().
 {
   return nonint_warning(arg,val,"of bitwise 'or' operation is not an integer");
 }
static long depth_cs () static
depth_cs
Depth of choice point stack
Definition at line 47 of file error.c.
References choice_stack, and wl_choice_point::next.
 {
   long i=0;
   ptr_choice_point c=choice_stack;
   while (c) { i++; c=c->next; }
   return i;
 }
static long depth_gs () static
depth_gs
Depth of goal stack
Definition at line 33 of file error.c.
References goal_stack, and wl_goal::next.
 {
   long i=0;
   ptr_goal g=goal_stack;
   while (g) { i++; g=g->next; }
   return i;
 }
static long depth_ts () static
depth_ts
Depth of trail (undo) stack
Definition at line 62 of file error.c.
References wl_stack::next, and undo_stack.
 {
   ptr_stack t=undo_stack;
   long i=0;
   while (t) { i++; t=t->next; }
   return i;
 }
void Errorline (char * format, ...)
Errorline.
Parameters
format - char *format
... New error printing routine
Definition at line 465 of file error.c.
References assert, display_psi(), FALSE, input_file_name, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), and psi_term_line_number.
 {
   va_list VarArg;
   //  int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   //  fprintf(stderr,"format = %lx %s\n",(long)format,format);fflush(stdout);
   fprintf(stderr,"*** Error: ");
   //  fprintf(stderr,"format2 = %lx %s\n",(long)format,format);
   // vinfoline(format, stderr, VarArg);
   //#define vinfoline(format, stderr, xxxx)  {
   for (p=format;p &&  *p; p++)
     {
       if (*p == '%')
     {
       p++;
       switch (*p)
         {
         case 'd':
         case 'x':
           buffer_loc[0] = '%';
           buffer_loc[1] = 'l';
           buffer_loc[2] = *p;
           buffer_loc[3] = 0;
           lng2 = va_arg(VarArg,long);
           fprintf(stderr, buffer_loc, lng2);
           break;
         case 's':
           buffer_loc[0] = '%';
           buffer_loc[1] = *p;
           buffer_loc[2] = 0;
           cptr = va_arg(VarArg,char *);
           fprintf(stderr, buffer_loc, cptr);
           break;
         case 'C':
           /* type coding as bin string */
           pil = va_arg(VarArg,ptr_int_list);
           print_code(stderr,pil);
           break;
         case 'P':
           psi = va_arg(VarArg,ptr_psi_term);
           display_psi(stderr,psi);
           break;
         case 'O':
           kind = va_arg(VarArg,operator);
           print_operator_kind(stderr,kind);
           break;
         case 'T':
           assert(stderr==stderr);
           t = va_arg(VarArg,def_type);
           print_def_type(t);
           break;
         case 'E':
           assert(stderr==stderr);
           perr_i("near line %ld",psi_term_line_number);
           if (strcmp(input_file_name,"stdin")) {
         perr_s(" in file \042%s\042",input_file_name);
           }
           parse_ok=FALSE;
           break;
         case '%':
           (void)putc(*p,stderr);
           break;
         default:
           fprintf(stderr,"<%c follows %% : report bug >", *p);
           break;
         }
     }
       else
     (void)putc(*p,stderr);
     }
   va_end(VarArg);
 #ifdef CLIFE
   exit(0);
 #endif
 }
void infoline (char * format, ...)
infoline
Parameters
format - char *format
...
Definition at line 281 of file error.c.
References assert, display_psi(), FALSE, input_file_name, NOTQUIET, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), and psi_term_line_number.
 {
   va_list VarArg;
   //  int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   if (NOTQUIET)
     {
       //      vinfoline(format, stdout, VarArg);
       //#define vinfoline(format, outfile, xxxx)  {
       for (p=format;p &&  *p; p++)
     {
       if (*p == '%')
         {
           p++;
           switch (*p)
         {
         case 'd':
         case 'x':
           buffer_loc[0] = '%';
           buffer_loc[1] = 'l';
           buffer_loc[2] = *p;
           buffer_loc[3] = 0;
           lng2 = va_arg(VarArg,long);
           fprintf(stdout, buffer_loc, lng2);
           break;
         case 's':
           buffer_loc[0] = '%';
           buffer_loc[1] = *p;
           buffer_loc[2] = 0;
           cptr = va_arg(VarArg,char *);
           fprintf(stdout, buffer_loc, cptr);
           break;
         case 'C':
           /* type coding as bin string */
           pil = va_arg(VarArg,ptr_int_list);
           print_code(stdout,pil);
           break;
         case 'P':
           psi = va_arg(VarArg,ptr_psi_term);
           display_psi(stdout,psi);
           break;
         case 'O':
           kind = va_arg(VarArg,operator);
           print_operator_kind(stdout,kind);
           break;
         case 'T':
           assert(stdout==stderr);
           t = va_arg(VarArg,def_type);
           print_def_type(t);
           break;
         case 'E':
           assert(stdout==stderr);
           perr_i("near line %ld",psi_term_line_number);
           if (strcmp(input_file_name,"stdin")) {
             perr_s(" in file 042%s042",input_file_name);
           }
           parse_ok=FALSE;
           break;
         case '%':
           (void)putc(*p,stdout);
           break;
         default:
           fprintf(stdout,"<%c follows %% : report bug >", *p);
           break;
         }
         }
       else
         (void)putc(*p,stdout);
     }
     }
   va_end(VarArg);
 }
void init_trace ()
init_trace
Initialize all tracing variables
Definition at line 651 of file error.c.
References FALSE, stepcount, stepflag, and trace.
 {
   trace=FALSE;
   stepflag=FALSE;
   stepcount=0;
 }
long int_div_warning (ptr_psi_term arg, REAL val)
int_div_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
Definition at line 1028 of file error.c.
References nonint_warning().
 {
   return nonint_warning(arg,val,"of integer division is not an integer");
 }
long mod_warning (ptr_psi_term arg, REAL val, int zero)
mod_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
zero - int zero
Definition at line 1041 of file error.c.
References Errorline(), nonint_warning(), and TRUE.
 {
   int err;
   err=nonint_warning(arg,val,"of modulo operation is not an integer");
   if(!err && zero && val==0) {
     Errorline("division by 0 in modulo operation\n");
     err=TRUE;
   }
   return err;
 }
void new_step (long newstep)
new_step
long newstep
Definition at line 713 of file error.c.
References FALSE, new_trace(), stepflag, and steptrace.
 {
   stepflag = newstep;
   printf("*** Single stepping is turned ");
   printf(stepflag?"on.\n":"off.\n");
   new_trace(stepflag);
   steptrace=FALSE;
 }
void new_trace (long newtrace)
new_trace
Parameters
newtrace - long newtrace
Definition at line 698 of file error.c.
References trace.
 {
   trace = newtrace;
   printf("*** Tracing is turned ");
   printf(trace?"on.":"off.");
   if (trace == 2) printf(" Only for Proves");
   printf("\n");
 }
long nonint_warning (ptr_psi_term arg, REAL val, char * msg)
nonint_warning
Parameters
arg - ptr_psi_term arg
val - REAL val
msg - char *msg
Definition at line 974 of file error.c.
References FALSE, report_warning2(), and TRUE.
 {
   long err=FALSE;
   if (val!=floor(val)) {
     report_warning2(arg, msg);
     err=TRUE;
   }
   return err;
 }
void nonnum_warning (ptr_psi_term t, ptr_psi_term arg1, ptr_psi_term arg2)
nonnum_warning
Parameters
t - ptr_psi_term t
arg1 - ptr_psi_term arg1
arg2 - ptr_psi_term arg2
Give error message if there is an argument which cannot unify with/ a real number.
Definition at line 953 of file error.c.
References curried, overlap_type(), real, report_warning(), and wl_psi_term::type.
 {
   if (!curried && /* PVR 15.9.93 */
       ((arg1 && !overlap_type(arg1->type,real)) ||
        (arg2 && !overlap_type(arg2->type,real)))) {
     report_warning(t,"non-numeric argument(s)");
   }
 }
void outputline (char * format, ...)
void outputline(char *format,...)
outputline
Parameters
format - char *format
...
Definition at line 101 of file error.c.
References assert, display_psi(), FALSE, input_file_name, output_stream, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), and psi_term_line_number.
 {
   va_list VarArg;
   // int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   //  vinfoline(format,output_stream, VarArg);
   //  #define vinfoline(format, outfile, xxxx)  {
   for (p=format;p &&  *p; p++)
     {
       if (*p == '%')
     {
       p++;
       switch (*p)
         {
         case 'd':
         case 'x':
           buffer_loc[0] = '%';
           buffer_loc[1] = 'l';
           buffer_loc[2] = *p;
           buffer_loc[3] = 0;
           lng2 = va_arg(VarArg, long);
           fprintf(output_stream, buffer_loc, lng2);
           break;
         case 's':
           buffer_loc[0] = '%';
           buffer_loc[1] = *p;
           buffer_loc[2] = 0;
           cptr = va_arg(VarArg,char *);
           fprintf(output_stream, buffer_loc, cptr);
           break;
         case 'C':
           /* type coding as bin string */
           pil = va_arg(VarArg,ptr_int_list);
           print_code(output_stream,pil);
           break;
         case 'P':
           psi = va_arg(VarArg,ptr_psi_term);
           display_psi(output_stream,psi);
           break;
         case 'O':
           kind = va_arg(VarArg,operator);
           print_operator_kind(output_stream,kind);
           break;
         case 'T':
           assert(output_stream==stderr);
           t = va_arg(VarArg,def_type);
           print_def_type(t);
           break;
         case 'E':
           assert(output_stream==stderr);
           perr_i("near line %ld",psi_term_line_number);
           if (strcmp(input_file_name,"stdin")) {
         perr_s(" in file \042%s\042",input_file_name);
           }
           parse_ok=FALSE;
           break;
         case '%':
           (void)putc(*p,output_stream);
           break;
         default:
           fprintf(output_stream,"<%c follows %% : report bug >", *p);
           break;
         }
     }
       else
     (void)putc(*p,output_stream);
     }
   va_end(VarArg);
 }
void perr (char * str)
perr
Parameters
str - char *str
Definition at line 763 of file error.c.
 {
   (void)fputs(str, stderr);
 }
void perr_i (char * str, long i)
perr_i
Parameters
str - char *str
i - long i
Definition at line 800 of file error.c.
 {
   fprintf(stderr,str,i);
 }
void perr_s (char * s1, char * s2)
perr_s
Parameters
s1 - char *s1
s2 - char *s2
Definition at line 775 of file error.c.
 {
   fprintf(stderr,s1,s2);
 }
void perr_s2 (char * s1, char * s2, char * s3)
perr_s2
Parameters
s1 - char *s1
s2 - char *s2
s3 - char *s3
Definition at line 788 of file error.c.
 {
   fprintf(stderr,s1,s2,s3);
 }
void report_error (ptr_psi_term g, char * s)
report_error
Parameters
g - ptr_psi_term g
s - char *s
REPORT_ERROR(g,s) Print an appropriate error message. G is the psi-term which caused the error, S a message to print. Format: '*** Error: s in 'g'.'
Definition at line 856 of file error.c.
References report_error_main().
 {
   report_error_main(g,s,"Error");
 }
void report_error2 (ptr_psi_term g, char * s)
report_error2
Parameters
g - ptr_psi_term g
s - char *s
REPORT_ERROR2(g,s) Like report_error, with a slightly different format. Format: '*** Error: argument 'g' s.'
Definition at line 923 of file error.c.
References report_error2_main().
 {
   report_error2_main(g,s,"Error");
 }
void report_error2_main (ptr_psi_term g, char * s, char * s2)
report_error2_main
Parameters
g - ptr_psi_term g
s - char *s
s2 - char *s2
Main routine for report_error2 and report_warning2
Definition at line 904 of file error.c.
References display_psi_stderr(), and perr_s().
 {
   //  FILE *f;
   perr_s("*** %s: argument '",s2);
   display_psi_stderr(g);
   perr_s("' %s.\n",s);
 }
void report_error_main (ptr_psi_term g, char * s, char * s2)
report_error_main
Parameters
g - ptr_psi_term g
s - char *s
s2 - char *s2
Main routine for report_error and report_warning
Definition at line 836 of file error.c.
References display_psi_stderr(), perr(), and perr_s2().
 {
   //  FILE *f;
   perr_s2("*** %s: %s in '",s2,s);
   display_psi_stderr(g);
   perr("'.\n");
 }
void report_warning (ptr_psi_term g, char * s)
report_warning
Parameters
g - ptr_psi_term g
s - char *s
REPORT_WARNING(g,s) Print an appropriate error message. G is the psi-term which caused the error, S a message to print. Format: '*** Warning: s in 'g'.'
Definition at line 890 of file error.c.
References report_error_main(), and warningflag.
 {
   if (warningflag) report_error_main(g,s,"Warning");
 }
void report_warning2 (ptr_psi_term g, char * s)
report_warning2
Parameters
g - ptr_psi_term g
s - char *s
REPORT_WARNING2(g,s) Like report_warning, with a slightly different format. Format: '*** Warning: argument 'g' s.'
Definition at line 938 of file error.c.
References report_error2_main(), and warningflag.
 {
   if (warningflag) report_error2_main(g,s,"Warning");
 }
long reportAndAbort (ptr_psi_term g, char * s)
reportAndAbort
Parameters
g - ptr_psi_term g
s - char *s
REPORTANDABORT(g,s) Print an appropriate error message. G is the psi-term which caused the error, S a message to print. Format: '*** Error: s in 'g'.'
Definition at line 872 of file error.c.
References abort_life(), report_error_main(), and TRUE.
 {
   report_error_main(g,s,"Error");
   return abort_life(TRUE); // djd added TRUE
 }
void reset_step ()
reset_step
Reset stepcount to zero Should be called when prompt is printed
Definition at line 665 of file error.c.
References stepcount, stepflag, and TRUE.
 {
   if (stepcount>0) {
     stepcount=0;
     stepflag=TRUE;
   }
 }
void set_trace_to_prove ()
set_trace_to_prove
void set_trace_to_prove()
Definition at line 727 of file error.c.
References new_trace().
 {
   new_trace(2);
 }
long shift_warning (long dir, ptr_psi_term arg, REAL val)
shift_warning
Parameters
dir - long dir
arg - ptr_psi_term arg
val - REAL val
Definition at line 1061 of file error.c.
References nonint_warning().
 {
   if (dir)
     return nonint_warning(arg,val,"of right shift operation is not an integer");
   else
     return nonint_warning(arg,val,"of left shift operation is not an integer");
 }
void stack_info (FILE * outfile)
stack_info
Parameters
outfile - FILE *outfile
Definition at line 77 of file error.c.
References depth_cs(), depth_gs(), depth_ts(), and verbose.
 {
   /* Information about size of embedded stacks */
   if (verbose) {
     long gn,cn,tn;
     fprintf(outfile,"*** Stack depths [");
     gn=depth_gs();
     cn=depth_cs();
     tn=depth_ts();
     fprintf(outfile,"%ld goal%s, %ld choice point%s, %ld trail entr%s",
             gn,(gn!=1?"s":""),
             cn,(cn!=1?"s":""),
             tn,(tn!=1?"ies":"y"));
     fprintf(outfile,"]\n");
   }
 }
void Syntaxerrorline (char * format, ...)
Syntaxerrorline.
Parameters
format - char *format
...
Definition at line 557 of file error.c.
References assert, display_psi(), FALSE, input_file_name, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), and psi_term_line_number.
 {
   va_list VarArg;
   //  int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   //  fprintf(stderr,"format = %lx %s\n",(long)format,format);fflush(stdout);
   if(parse_ok) { /*  RM: Feb  1 1993  */
     parse_ok=FALSE; /*  RM: Feb  1 1993  */
     fprintf(stderr,"*** Syntax error: ");
     //    fprintf(stderr,"format2 = %lx %s\n",(long)format,format);
     // vinfoline(format, stderr, VarArg);
     //#define vinfoline(format, outfile, xxxx)  {
     for (p=format;p &&  *p; p++)
       {
     if (*p == '%')
       {
         p++;
         switch (*p)
           {
           case 'd':
           case 'x':
         buffer_loc[0] = '%';
         buffer_loc[1] = 'l';
         buffer_loc[2] = *p;
         buffer_loc[3] = 0;
         lng2 = va_arg(VarArg,long);
         fprintf(stderr, buffer_loc, lng2);
         break;
           case 's':
         buffer_loc[0] = '%';
         buffer_loc[1] = *p;
         buffer_loc[2] = 0;
         cptr = va_arg(VarArg,char *);
         fprintf(stderr, buffer_loc, cptr);
         break;
           case 'C':
         /* type coding as bin string */
         pil = va_arg(VarArg,ptr_int_list);
         print_code(stderr,pil);
         break;
           case 'P':
         psi = va_arg(VarArg,ptr_psi_term);
         display_psi(stderr,psi);
         break;
           case 'O':
         kind = va_arg(VarArg,operator);
         print_operator_kind(stderr,kind);
         break;
           case 'T':
         assert(stderr==stderr);
         t = va_arg(VarArg,def_type);
         print_def_type(t);
         break;
           case 'E':
         assert(stderr==stderr);
         perr_i("near line %ld",psi_term_line_number);
         if (strcmp(input_file_name,"stdin")) {
           perr_s(" in file \042%s\042",input_file_name);
         }
         parse_ok=FALSE;
         break;
           case '%':
         (void)putc(*p,stderr);
         break;
           default:
         fprintf(stderr,"<%c follows %% : report bug >", *p);
         break;
           }
       }
     else
       (void)putc(*p,stderr);
       }
   }
   va_end(VarArg);
 }
void toggle_step ()
toggle_step
Definition at line 747 of file error.c.
References new_step(), and stepflag.
 {
   new_step(!stepflag);
 }
void toggle_trace ()
toggle_trace
Definition at line 737 of file error.c.
References new_trace(), and trace.
 {
   new_trace(trace?0:1);
 }
void traceline (char * format, ...)
traceline
Parameters
format - char *format
...
Definition at line 186 of file error.c.
References assert, display_psi(), FALSE, input_file_name, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), psi_term_line_number, trace, and tracing().
 {
   va_list VarArg;
   //  int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   if (trace) // DJD
     {
       /* RM: Nov 10 1993  */
       if ((trace == 2) && (format[0] != 'p')) return;
       tracing();
       //      vinfoline(format, stdout, VarArg);
       // #define vinfoline(format, outfile, xxxx)  {
       for (p=format;p &&  *p; p++)
     {
       if (*p == '%')
         {
           p++;
           switch (*p)
         {
         case 'd':
         case 'x':
           buffer_loc[0] = '%';
           buffer_loc[1] = 'l';
           buffer_loc[2] = *p;
           buffer_loc[3] = 0;
           lng2 = va_arg(VarArg, long);
           fprintf(stdout, buffer_loc, lng2);
           break;
         case 's':
           buffer_loc[0] = '%';
           buffer_loc[1] = *p;
           buffer_loc[2] = 0;
           cptr = va_arg(VarArg,char *);
           fprintf(stdout, buffer_loc, cptr);
           break;
         case 'C':
           /* type coding as bin string */
           pil = va_arg(VarArg,ptr_int_list);
           print_code(stdout,pil);
           break;
         case 'P':
           psi = va_arg(VarArg,ptr_psi_term);
           display_psi(stdout,psi);
           break;
         case 'O':
           kind = va_arg(VarArg,operator);
           print_operator_kind(stdout,kind);
           break;
         case 'T':
           assert(stdout==stderr);
           t = va_arg(VarArg,def_type);
           print_def_type(t);
           break;
         case 'E':
           assert(stdout==stderr);
           perr_i("near line %ld",psi_term_line_number);
           if (strcmp(input_file_name,"stdin")) {
             perr_s(" in file \042%s\042",input_file_name);
           }
           parse_ok=FALSE;
           break;
         case '%':
           (void)putc(*p,stdout);
           break;
         default:
           fprintf(stdout,"<%c follows %% : report bug >", *p);
           break;
         }
         }
       else
         (void)putc(*p,stdout);
     }
     }
   va_end(VarArg);
 }
void tracing ()
tracing
Definition at line 678 of file error.c.
References depth_cs(), depth_gs(), goal_count, MAX_TRACE_INDENT, steptrace, and TRUE.
 {
   long i;
   long indent_loc;
   printf("T%04ld",goal_count);
   printf(" C%02ld",depth_cs());
   indent_loc=depth_gs();
   if (indent_loc>=MAX_TRACE_INDENT) printf(" G%02ld",indent_loc);
   indent_loc = indent_loc % MAX_TRACE_INDENT;
   for (i=indent_loc; i>=0; i--) printf(" ");
   steptrace=TRUE;
 }
long warning ()
warning
Definition at line 810 of file error.c.
References perr(), and warningflag.
 {
   if (warningflag) perr("*** Warning: ");
   return warningflag;
 }
void warningline (char * format, ...)
warningline
Parameters
format - char *format
...
Definition at line 371 of file error.c.
References assert, display_psi(), FALSE, input_file_name, parse_ok, perr_i(), perr_s(), print_code(), print_def_type(), print_operator_kind(), psi_term_line_number, quietflag, and warningflag.
 {
   va_list VarArg;
   //  int l;
   char buffer_loc[5];
   char *p;
   unsigned long lng2;
   char *cptr;
   ptr_int_list pil;
   ptr_psi_term psi;
   operator kind;
   def_type t ;
   va_start(VarArg,format);
   if (warningflag) { // macro would not work
     if(quietflag) return; /*  RM: Sep 24 1993  */
     fprintf(stderr,"*** Warning: ");
     //    vinfoline(format, stderr, VarArg);
     // #define vinfoline(format, stderr, xxxx)  {
     for (p=format;p &&  *p; p++)
       {
     if (*p == '%')
       {
         p++;
         switch (*p)
           {
           case 'd':
           case 'x':
         buffer_loc[0] = '%';
         buffer_loc[1] = 'l';
         buffer_loc[2] = *p;
         buffer_loc[3] = 0;
         lng2 = va_arg(VarArg,long);
         fprintf(stderr, buffer_loc, lng2);
         break;
           case 's':
         buffer_loc[0] = '%';
         buffer_loc[1] = *p;
         buffer_loc[2] = 0;
         cptr = va_arg(VarArg,char *);
         fprintf(stderr, buffer_loc, cptr);
         break;
           case 'C':
         /* type coding as bin string */
         pil = va_arg(VarArg,ptr_int_list);
         print_code(stderr,pil);
         break;
           case 'P':
         psi = va_arg(VarArg,ptr_psi_term);
         display_psi(stderr,psi);
         break;
           case 'O':
         kind = va_arg(VarArg,operator);
         print_operator_kind(stderr,kind);
         break;
           case 'T':
         assert(stderr==stderr);
         t = va_arg(VarArg,def_type);
         print_def_type(t);
         break;
           case 'E':
         assert(stderr==stderr);
         perr_i("near line %ld",psi_term_line_number);
         if (strcmp(input_file_name,"stdin")) {
           perr_s(" in file 042%s042",input_file_name);
         }
         parse_ok=FALSE;
         break;
           case '%':
         (void)putc(*p,stderr);
         break;
           default:
         fprintf(stderr,"<%c follows %% : report bug >", *p);
         break;
           }
       }
     else
       (void)putc(*p,stderr);
       }
   }
   va_end(VarArg);
 }
long warningx ()
warningx
Definition at line 821 of file error.c.
References perr(), and warningflag.
 {
   if (warningflag) perr("*** Warning");
   return warningflag;
 }
Variable Documentation
long quietflag =FALSE
Definition at line 20 of file error.c.
long stepcount = 0
Definition at line 25 of file error.c.
long stepflag = 0
Definition at line 23 of file error.c.
long steptrace = 0
Definition at line 24 of file error.c.
long trace =FALSE
Definition at line 21 of file error.c.
long verbose =FALSE
Definition at line 22 of file error.c.
long warningflag =TRUE
Definition at line 19 of file error.c.