Wild Life: xdisplaylist.c File Reference
xdisplaylist.c File Reference
x windows display functions
Data Structures
struct wl_Line
struct wl_Rectangle
struct wl_Arc
struct wl_String
struct wl_GraphicClosure
struct wl_PostScriptClosure
struct wl_Polygon
union wl_DisplayElt
Macros
#define AllocDisplayElt() malloc (sizeof (DisplayElt))
#define FreeDisplayElt(E) free (E)
#define BUF_SIZE 512
Typedefs
typedef struct wl_Line Line
typedef struct wl_Rectangle Rectangle
typedef struct wl_Arc Arc
typedef struct wl_String String
typedef struct wl_GraphicClosure GraphicClosure
typedef struct wl_PostScriptClosure PostScriptClosure
typedef struct wl_Polygon Polygon
typedef union wl_DisplayElt DisplayElt
typedef DisplayElt * RefDisplayElt
Functions
static ListLinks * x_get_links_of_display_list (DisplayElt *elt)
x_get_links_of_display_list
ListHeader * x_display_list ()
x_display_list
void x_set_gc (Display *display, GC gc, long function, unsigned long color, long linewidth, Font font)
x_set_gc
void x_record_line (ListHeader *displaylist, Action action, long x0, long y0, long x1, long y1, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_line
void x_record_arc (ListHeader *displaylist, Action action, long x, long y, long width, long height, long startangle, long arcangle, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_arc
void x_record_rectangle (ListHeader *displaylist, Action action, long x, long y, long width, long height, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_rectangle
void x_record_polygon (ListHeader *displaylist, Action action, XPoint *points, long npoints, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_polygon
void x_record_string (ListHeader *displaylist, Action action, long x, long y, char *str, Font font, unsigned long function, unsigned long color)
x_record_string
static long x_draw_elt (DisplayElt *elt, GraphicClosure *g)
x_draw_elt
void x_refresh_window (Display *display, Window window, Pixmap pixmap, GC pixmapgc, ListHeader *displaylist)
x_refresh_window
static long x_free_elt (DisplayElt *elt, long *closure)
x_free_elt
void x_free_display_list (ListHeader *displaylist)
x_free_display_list
static void x_postscript_prolog (long f)
x_postscript_prolog
static char * add_number (char *buf, long n)
add_number
static char * add_string (char *buf, char *s)
add_string
static void x_get_rgb_values (Display *display, Window window, unsigned long color, XColor *rgb)
x_get_rgb_values
static long x_postscript_elt (DisplayElt *elt, PostScriptClosure *psc)
x_postscript_elt
long x_postscript_window (Display *display, Window window, ListHeader *displaylist, char *filename)
x_postscript_window
Variables
static char * prolog []
static char nstr [BUF_SIZE]
Detailed Description
x windows display functions
Definition in file xdisplaylist.c.
Macro Definition Documentation
#define AllocDisplayElt () malloc (sizeof (DisplayElt))
Definition at line 169 of file xdisplaylist.c.
#define BUF_SIZE 512
Definition at line 610 of file xdisplaylist.c.
#define FreeDisplayElt (E) free (E)
Definition at line 170 of file xdisplaylist.c.
Typedef Documentation
typedef struct wl_Arc Arc
typedef union wl_DisplayElt DisplayElt
typedef struct wl_GraphicClosure GraphicClosure
typedef struct wl_Line Line
typedef struct wl_Polygon Polygon
typedef struct wl_PostScriptClosure PostScriptClosure
typedef struct wl_Rectangle Rectangle
typedef DisplayElt* RefDisplayElt
Definition at line 99 of file xdisplaylist.c.
typedef struct wl_String String
Function Documentation
static char * add_number (char * buf, long n) static
add_number
Parameters
buf - char *buf
n - long n
Definition at line 621 of file xdisplaylist.c.
References BUF_SIZE, and nstr.
 {
     long m, i;
     char *s;
     for (m=n, i=1; m>=10; i++)
         m /= 10;
     if (i < BUF_SIZE && strlen (buf) + i < BUF_SIZE)
     {
     sprintf (nstr, "%ld ", n);
     strcat (buf, nstr);
     }
     return buf;
 }
static char * add_string (char * buf, char * s) static
add_string
Parameters
buf - char *buf
s - char *s
Definition at line 645 of file xdisplaylist.c.
References BUF_SIZE.
 {
     if (strlen (buf) + strlen(s) < BUF_SIZE)
     strcat (buf, s);
     return buf;
 }
ListHeader * x_display_list ()
x_display_list
Definition at line 120 of file xdisplaylist.c.
References List_SetLinkProc(), and x_get_links_of_display_list().
 {
     ListHeader *display_list;
     display_list = (ListHeader *) malloc (sizeof (ListHeader));
     List_SetLinkProc (display_list, x_get_links_of_display_list);
     return display_list;
 }
static long x_draw_elt (DisplayElt * elt, GraphicClosure * g) static
x_draw_elt
Parameters
elt - DisplayElt *elt
g - GraphicClosure *g
Definition at line 344 of file xdisplaylist.c.
References wl_Rectangle::action, wl_Arc::action, wl_String::action, wl_Polygon::action, wl_DisplayElt::action, wl_Arc::arcangle, wl_Line::color, wl_Rectangle::color, wl_Arc::color, wl_String::color, wl_Polygon::color, wl_GraphicClosure::display, wl_GraphicClosure::drawable, wl_String::font, wl_Line::function, wl_Rectangle::function, wl_Arc::function, wl_String::function, wl_Polygon::function, wl_GraphicClosure::gc, wl_Rectangle::height, wl_Arc::height, wl_Line::linewidth, wl_Rectangle::linewidth, wl_Arc::linewidth, wl_Polygon::linewidth, wl_Polygon::npoints, wl_Polygon::points, wl_Arc::startangle, wl_String::str, TRUE, wl_Rectangle::width, wl_Arc::width, wl_Rectangle::x, wl_Arc::x, wl_String::x, wl_Line::x0, wl_Line::x1, x_set_gc(), xDefaultFont, xDefaultLineWidth, wl_Rectangle::y, wl_Arc::y, wl_String::y, wl_Line::y0, and wl_Line::y1.
 {
     Line *line;
     Arc *arc;
     Rectangle *rectangle;
     String *s;
     Polygon *polygon;
     switch (elt->action)
     {
         case DRAW_LINE:
         line = (Line *) elt;
         x_set_gc (g->display, g->gc, line->function,
               line->color, line->linewidth, xDefaultFont);
         XDrawLine (g->display, g->drawable, g->gc,
                line->x0, line->y0, line->x1, line->y1);
         break;
         case DRAW_ARC:
         case FILL_ARC:
         arc = (Arc *) elt;
         x_set_gc (g->display, g->gc, arc->function,
               arc->color, arc->linewidth, xDefaultFont);
         if (arc->action == DRAW_ARC)
             XDrawArc (g->display, g->drawable, g->gc,
               arc->x, arc->y,
               arc->width, arc->height,
               arc->startangle, arc->arcangle);
         else
             XFillArc (g->display, g->drawable, g->gc,
               arc->x, arc->y,
               arc->width, arc->height,
               arc->startangle, arc->arcangle);
         break;
         case DRAW_RECTANGLE:
         case FILL_RECTANGLE:
         rectangle = (Rectangle *) elt;
         x_set_gc (g->display, g->gc, rectangle->function,
               rectangle->color, rectangle->linewidth, xDefaultFont);
         if (rectangle->action == DRAW_RECTANGLE)
             XDrawRectangle (g->display, g->drawable, g->gc,
                 rectangle->x, rectangle->y,
                 rectangle->width, rectangle->height);
         else
             XFillRectangle (g->display, g->drawable, g->gc,
                 rectangle->x, rectangle->y,
                 rectangle->width, rectangle->height);
         break;
         case DRAW_STRING:
         case DRAW_IMAGE_STRING:
         s = (String *) elt;
         x_set_gc (g->display, g->gc, s->function,
               s->color, xDefaultLineWidth, s->font);
         if (s->action == DRAW_STRING)
             XDrawString (g->display, g->drawable, g->gc,
                  s->x, s->y,
                  s->str, strlen (s->str));
         else
             XDrawImageString (g->display, g->drawable, g->gc,
                  s->x, s->y,
                  s->str, strlen (s->str));
         break;
         case DRAW_POLYGON:
         case FILL_POLYGON:
         polygon = (Polygon *) elt;
         x_set_gc (g->display, g->gc, polygon->function,
               polygon->color, polygon->linewidth, xDefaultFont);
         if (polygon->action == FILL_POLYGON)
             XFillPolygon (g->display, g->drawable, g->gc,
                   polygon->points, polygon->npoints,
                   Complex, CoordModeOrigin);
         else
             XDrawLines   (g->display, g->drawable, g->gc,
                   polygon->points, polygon->npoints,
                   CoordModeOrigin);
         break;
     }
     return TRUE;
 }
void x_free_display_list (ListHeader * displaylist)
x_free_display_list
Parameters
displaylist - ListHeader *displaylist
Definition at line 548 of file xdisplaylist.c.
References List_Enum(), NULL, and x_free_elt().
 {
   List_Enum (displaylist,( RefListEnumProc)x_free_elt, NULL);
 }
static long x_free_elt (DisplayElt * elt, long * closure) static
x_free_elt
Parameters
elt - DisplayElt *elt
closure - long *closure
Definition at line 494 of file xdisplaylist.c.
References wl_DisplayElt::action, FreeDisplayElt, wl_Polygon::points, wl_String::str, and TRUE.
 {
     Line *line;
     Arc *arc;
     Rectangle *rectangle;
     String *s;
     Polygon *polygon;
     /* free the attributes of the element */
     switch (elt->action)
     {
         case DRAW_LINE:
         /* no attribute to free ? */
         break;
         case DRAW_ARC:
         case FILL_ARC:
         /* no attribute to free ? */
         break;
         case DRAW_RECTANGLE:
         case FILL_RECTANGLE:
         /* no attribute to free ? */
         break;
         case DRAW_STRING:
         case DRAW_IMAGE_STRING:
         s = (String *) elt;
         free (s->str);
         break;
         case DRAW_POLYGON:
         case FILL_POLYGON:
         polygon = (Polygon *) elt;
         free (polygon->points);
         break;
     }
     /* finaly, free the element itself */
     FreeDisplayElt (elt);
     return TRUE;
 }
static ListLinks * x_get_links_of_display_list (DisplayElt * elt) static
x_get_links_of_display_list
Parameters
elt - DisplayElt *elt
Definition at line 110 of file xdisplaylist.c.
 {
     return &((Line *) elt)->links;
 }
static void x_get_rgb_values (Display * display, Window window, unsigned long color, XColor * rgb) static
x_get_rgb_values
Parameters
display - Display *display
window - Window window
color -unsigned long color
rgb - XColor *rgb
Definition at line 662 of file xdisplaylist.c.
 {
     XWindowAttributes windowAttributes;
     XGetWindowAttributes (display, window, &windowAttributes);
     rgb->pixel = color;
     XQueryColor (display, windowAttributes.colormap, rgb);
 }
static long x_postscript_elt (DisplayElt * elt, PostScriptClosure * psc) static
x_postscript_elt
Parameters
elt - DisplayElt *elt
psc - PostScriptClosure *psc
Definition at line 678 of file xdisplaylist.c.
References wl_Rectangle::action, wl_Arc::action, wl_String::action, wl_DisplayElt::action, add_number(), add_string(), wl_Arc::arcangle, BUF_SIZE, wl_Line::color, wl_Rectangle::color, wl_Arc::color, wl_String::color, wl_Polygon::color, wl_PostScriptClosure::display, wl_PostScriptClosure::f, wl_Rectangle::height, wl_Arc::height, wl_PostScriptClosure::height, wl_Line::linewidth, wl_Rectangle::linewidth, wl_Arc::linewidth, wl_Polygon::npoints, wl_Polygon::points, wl_Arc::startangle, wl_String::str, TRUE, wl_Rectangle::width, wl_Arc::width, wl_PostScriptClosure::window, wl_Rectangle::x, wl_Arc::x, wl_String::x, wl_Line::x0, wl_Line::x1, x_get_rgb_values(), wl_Rectangle::y, wl_Arc::y, wl_String::y, wl_Line::y0, and wl_Line::y1.
 {
     Line *line;
     Arc *arc;
     Rectangle *rectangle;
     String *s;
     Polygon *polygon;
     char buf[BUF_SIZE];
     char *pbuf;
     XPoint *p;
     XColor color;
     long i;
     int ret; // added bacause of compiler warning - should be checked below
     buf[0] = 0;
     pbuf = buf;
     switch (elt->action)
     {
         case DRAW_LINE:
         line = (Line *) elt;
         pbuf = add_number (pbuf, line->x0);
         pbuf = add_number (pbuf, psc->height - line->y0);
         pbuf = add_number (pbuf, line->x1);
         pbuf = add_number (pbuf, psc->height - line->y1);
         x_get_rgb_values ((Display *)psc->display, psc->window, line->color, &color); // added cast DJD
         pbuf = add_number (pbuf, color.red);
         pbuf = add_number (pbuf, color.green);
         pbuf = add_number (pbuf, color.blue);
         pbuf = add_number (pbuf, line->linewidth);
         pbuf = add_string (pbuf, "line\n");
         ret = write (psc->f, pbuf, strlen (pbuf));
         break;
         case DRAW_RECTANGLE:
         case FILL_RECTANGLE:
         rectangle = (Rectangle *) elt;
         pbuf = add_number (pbuf, rectangle->x);
         pbuf = add_number (pbuf, psc->height - rectangle->y);
         pbuf = add_number (pbuf, rectangle->width);
         pbuf = add_number (pbuf, rectangle->height);
         x_get_rgb_values ((Display *) psc->display, psc->window, rectangle->color, &color); // added cast DJD
         pbuf = add_number (pbuf, color.red);
         pbuf = add_number (pbuf, color.green);
         pbuf = add_number (pbuf, color.blue);
         if (rectangle->action == DRAW_RECTANGLE)
         {
         pbuf = add_number (pbuf, rectangle->linewidth);
         pbuf = add_string (pbuf, "true ");
         }
         else
         {
         pbuf = add_number (pbuf, 1);
         pbuf = add_string (pbuf, "false ");
         }
         pbuf = add_string (pbuf, "rect\n");
         ret = write (psc->f, pbuf, strlen (pbuf));
         break;
         case DRAW_ARC:
         case FILL_ARC:
         arc = (Arc *) elt;
         pbuf = add_number (pbuf, arc->x+arc->width/2);
         pbuf = add_number (pbuf, psc->height - (arc->y+arc->height/2));
         pbuf = add_number (pbuf, arc->width/2);
         pbuf = add_number (pbuf, arc->height/2);
         pbuf = add_number (pbuf, arc->startangle);
         pbuf = add_number (pbuf, (arc->startangle+arc->arcangle)/64);
         x_get_rgb_values ((Display *)psc->display, psc->window, arc->color, &color); // added cast DJD
         pbuf = add_number (pbuf, color.red);
         pbuf = add_number (pbuf, color.green);
         pbuf = add_number (pbuf, color.blue);
         if (arc->action == DRAW_ARC)
         {
         pbuf = add_number (pbuf, arc->linewidth);
         pbuf = add_string (pbuf, "true ");
         }
         else
         {
         pbuf = add_number (pbuf, 1);
         pbuf = add_string (pbuf, "false ");
         }
         pbuf = add_string (pbuf, "earc\n");
         ret = write (psc->f, pbuf, strlen (pbuf));
         break;
         case DRAW_STRING:
         case DRAW_IMAGE_STRING:
         s = (String *) elt;
         pbuf = add_number (pbuf, s->x);
         pbuf = add_number (pbuf, psc->height - s->y);
         pbuf = add_string (pbuf, "(");
         pbuf = add_string (pbuf, s->str);
         pbuf = add_string (pbuf, ") ");
         x_get_rgb_values ((Display *)psc->display, psc->window, s->color, &color); // added cast DJD
         pbuf = add_number (pbuf, color.red);
         pbuf = add_number (pbuf, color.green);
         pbuf = add_number (pbuf, color.blue);
         if (s->action == DRAW_STRING)
         pbuf = add_string (pbuf, "true ");
         else
         pbuf = add_string (pbuf, "false ");
         pbuf = add_string (pbuf, "dstr\n");
         ret = write (psc->f, pbuf, strlen (pbuf));
         break;
         case FILL_POLYGON:
         polygon = (Polygon *) elt;
         x_get_rgb_values ((Display *)psc->display, psc->window, polygon->color, &color); // added cast DJD
         pbuf = add_number (pbuf, color.red);
         pbuf = add_string (pbuf, "65535 div ");
         pbuf = add_number (pbuf, color.green);
         pbuf = add_string (pbuf, "65535 div ");
         pbuf = add_number (pbuf, color.blue);
         pbuf = add_string (pbuf, "65535 div ");
         pbuf = add_string (pbuf, "setrgbcolor ");
         p = polygon->points;
         pbuf = add_string (pbuf, "np ");
         pbuf = add_number (pbuf, p->x);
         pbuf = add_number (pbuf, psc->height - p->y);
         pbuf = add_string (pbuf, "mt\n");
         ++p;
         for (i=1; i<polygon->npoints; i++, p++)
         {
         pbuf = add_number (pbuf, p->x);
         pbuf = add_number (pbuf, psc->height - p->y);
         pbuf = add_string (pbuf, "lt ");
         if (i%4==0)
             pbuf = add_string (pbuf, "\n");
         }
         pbuf = add_string (pbuf, "cp fi\n");
         ret = write (psc->f, pbuf, strlen (pbuf));
         break;
     }
     return TRUE;
 }
static void x_postscript_prolog (long f) static
x_postscript_prolog
Parameters
f - long f
Definition at line 599 of file xdisplaylist.c.
References prolog.
 {
     long i;
     int ret; // added bacause of compiler warning - should be checked below
     for (i = 0; prolog[i] != 0; i++)
         ret = write (f, prolog[i], strlen (prolog[i]));
 }
long x_postscript_window (Display * display, Window window, ListHeader * displaylist, char * filename)
x_postscript_window
Parameters
display - Display *display
window - Window window
displaylist - ListHeader *displaylist
filename -char *filename
Definition at line 839 of file xdisplaylist.c.
References wl_PostScriptClosure::display, Errorline(), wl_PostScriptClosure::f, FALSE, wl_PostScriptClosure::height, List_Enum(), TRUE, wl_PostScriptClosure::window, x_postscript_elt(), and x_postscript_prolog().
 {
     XWindowAttributes windowAttributes;
     PostScriptClosure psc;
     int ret; // added bacause of compiler warning - should be checked below
     psc.display = (GENERIC)display;
     psc.window = window;
     if ((psc.f = open (filename, O_CREAT|O_WRONLY|O_TRUNC,
            S_IRUSR|S_IWUSR|S_IRWXG)) == -1)
     {
     Errorline ("\n*** Error: cannot open file %s.\n", filename);
     return FALSE;
     }
     XGetWindowAttributes (display, window, &windowAttributes);
     psc.height = windowAttributes.height;
     x_postscript_prolog (psc.f);
     List_Enum (displaylist,( RefListEnumProc)x_postscript_elt, &psc);
     ret = write (psc.f, "showpage\n", strlen ("showpage\n"));
     close (psc.f);
     return TRUE;
 }
void x_record_arc (ListHeader * displaylist, Action action, long x, long y, long width, long height, long startangle, long arcangle, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_arc
Parameters
displaylist - ListHeader *displaylist
action - Action action
x - long x
y - long y
width - long width
height - long height
startangle - long startangle
arcangle - long arcangle
function - unsigned long function
color - unsigned long color
linewidth - unsigned long linewidth
Definition at line 221 of file xdisplaylist.c.
References wl_Arc::action, AllocDisplayElt, wl_Arc::arcangle, wl_Arc::color, wl_Arc::function, wl_Arc::height, wl_Arc::linewidth, List_Append(), wl_Arc::startangle, wl_Arc::width, wl_Arc::x, and wl_Arc::y.
 {
     Arc * elt;
     elt = (Arc *) AllocDisplayElt ();
     elt->action = action;
     elt->x = x;
     elt->y = y;
     elt->width = width;
     elt->height = height;
     elt->startangle = startangle;
     elt->arcangle = arcangle;
     elt->function = function;
     elt->color = color;
     elt->linewidth = linewidth;
     List_Append (displaylist, (Ref) elt);
 }
void x_record_line (ListHeader * displaylist, Action action, long x0, long y0, long x1, long y1, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_line
Parameters
displaylist ListHeader *displaylist
action - Action action
x0 - long x0
y0 - long y0
x1 - long x1
y1 - long y1
function - unsigned long function
color - unsigned long color
linewidth - unsigned long linewidth
Definition at line 186 of file xdisplaylist.c.
References wl_Line::action, AllocDisplayElt, wl_Line::color, wl_Line::function, wl_Line::linewidth, List_Append(), wl_Line::x0, wl_Line::x1, wl_Line::y0, and wl_Line::y1.
 {
     Line * elt;
     elt = (Line *) AllocDisplayElt ();
     elt->action = action;
     elt->x0 = x0;
     elt->y0 = y0;
     elt->x1 = x1;
     elt->y1 = y1;
     elt->function = function;
     elt->color = color;
     elt->linewidth = linewidth;
     List_Append (displaylist, (Ref) elt);
 }
void x_record_polygon (ListHeader * displaylist, Action action, XPoint * points, long npoints, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_polygon
Parameters
displaylist - ListHeader *displaylist
action Action action
points - XPoint *points
npoints - long npoints
function - unsigned long function
color - unsigned long color
linewidth - unsigned long linewidth
Definition at line 285 of file xdisplaylist.c.
References wl_Polygon::action, AllocDisplayElt, wl_Polygon::color, wl_Polygon::function, wl_Polygon::linewidth, List_Append(), wl_Polygon::npoints, and wl_Polygon::points.
 {
     Polygon * elt;
     XPoint *p;
     elt = (Polygon *) AllocDisplayElt ();
     elt->action = action;
     elt->npoints = npoints;
     elt->points = p = (XPoint *) malloc (npoints*2*sizeof(short));
     for (; npoints > 0; npoints--, p++, points++)
         *p = *points;
     elt->function = function;
     elt->color = color;
     elt->linewidth = linewidth;
     List_Append (displaylist, (Ref) elt);
 }
void x_record_rectangle (ListHeader * displaylist, Action action, long x, long y, long width, long height, unsigned long function, unsigned long color, unsigned long linewidth)
x_record_rectangle
Parameters
displaylist - ListHeader *displaylist
action - Action action
x - long x
y - long y
width - long width
height - long height
function - unsigned long function
color - unsigned long color
linewidth - unsigned long linewidth
Definition at line 255 of file xdisplaylist.c.
References wl_Rectangle::action, AllocDisplayElt, wl_Rectangle::color, wl_Rectangle::function, wl_Rectangle::height, wl_Rectangle::linewidth, List_Append(), wl_Rectangle::width, wl_Rectangle::x, and wl_Rectangle::y.
 {
     Rectangle * elt;
     elt = (Rectangle *) AllocDisplayElt ();
     elt->action = action;
     elt->x = x;
     elt->y = y;
     elt->width = width;
     elt->height = height;
     elt->function = function;
     elt->color = color;
     elt->linewidth = linewidth;
     List_Append (displaylist, (Ref) elt);
 }
void x_record_string (ListHeader * displaylist, Action action, long x, long y, char * str, Font font, unsigned long function, unsigned long color)
x_record_string
Parameters
displaylist - ListHeader *displaylist
action - Action action
x - long x
y - long y
str - char *str
font - Font font
function - unsigned long function
color - unsigned long color
Definition at line 318 of file xdisplaylist.c.
References wl_String::action, AllocDisplayElt, wl_String::color, wl_String::font, wl_String::function, List_Append(), wl_String::str, wl_String::x, and wl_String::y.
 { // font & str order was reversed DJD
     String * elt;
     elt = (String *) AllocDisplayElt ();
     elt->action = action;
     elt->x = x;
     elt->y = y;
     elt->str = (char *) malloc (strlen (str)+1); /* 11.9 */
     strcpy (elt->str, str);
     *(elt->str+strlen(str)) = '\0';
     elt->function = function;
     elt->color = color;
     elt->font = font;
     List_Append (displaylist, (Ref) elt);
 }
void x_refresh_window (Display * display, Window window, Pixmap pixmap, GC pixmapgc, ListHeader * displaylist)
x_refresh_window
Parameters
display - Display *display
window - Window window
pixmap - Pixmap pixmap
pixmapgc - GC pixmapgc
displaylist - ListHeader *displaylist
Definition at line 447 of file xdisplaylist.c.
References wl_GraphicClosure::display, wl_GraphicClosure::drawable, wl_GraphicClosure::gc, List_Enum(), x_draw_elt(), x_set_gc(), xDefaultFont, and xDefaultLineWidth.
 {
     XWindowAttributes attr;
     GraphicClosure g;
     /* disable the GraphicsExpose emitted by XCopyArea */
     XSetGraphicsExposures (display, pixmapgc, False);
     /* get the geometry of the window */
     XGetWindowAttributes (display, window, &attr);
 #if 0
     /* does not work with a pixmap, only with windows !! @#@^&%#(*&! - jch */
     XClearArea (display, pixmap, 0, 0,
         attr.width, attr.height, False);
 #endif
     x_set_gc (display, pixmapgc, GXcopy, attr.backing_pixel,
           xDefaultLineWidth, xDefaultFont);
     XFillRectangle (display, pixmap, pixmapgc,
             0, 0, attr.width, attr.height);
     g.display = display;
     g.drawable = pixmap;
     g.gc = pixmapgc;
     List_Enum (displaylist,(RefListEnumProc) x_draw_elt, &g);
     if (window != pixmap)
         XCopyArea (display, pixmap, window, pixmapgc, 0, 0,
            attr.width, attr.height, 0, 0);
     XSync (display, 0);
 }
void x_set_gc (Display * display, GC gc, long function, unsigned long color, long linewidth, Font font)
x_set_gc
Parameters
display - Display *display
gc - GC gc
function - long function
color - unsigned long color
linewidth - long linewidth
font - Font font
Definition at line 142 of file xdisplaylist.c.
References xDefaultFont, and xDefaultLineWidth.
 {
     XGCValues gcvalues;
     unsigned long valuemask;
     gcvalues.function = function;
     gcvalues.foreground = color;
     valuemask = GCFunction | GCForeground;
     if (linewidth != xDefaultLineWidth)
     {
     gcvalues.line_width = linewidth;
     valuemask |= GCLineWidth;
     }
     if (font != xDefaultFont)
     {
     gcvalues.font = font;
     valuemask |= GCFont;
     }
     XChangeGC (display, gc, valuemask, &gcvalues);
 }
Variable Documentation
char nstr[BUF_SIZE] static
Definition at line 612 of file xdisplaylist.c.
char* prolog[] static
Definition at line 555 of file xdisplaylist.c.