Wild Life: bi_sys.c File Reference
bi_sys.c File Reference
Macros
#define copyPsiTerm(a, b) (ptr_psi_term)memcpy(a,b,sizeof(psi_term))
Functions
long c_trace ()
long c_tprove ()
static long c_step ()
static long c_verbose ()
static long c_warning ()
static long c_maxint ()
long c_quiet ()
static long c_cputime ()
static long c_realtime ()
static long c_localtime ()
static long c_statistics ()
static long c_garbage ()
static long c_getenv ()
static long c_system ()
static long c_encode ()
void setUnitList (GENERIC x)
ptr_psi_term unitListValue ()
GENERIC unitListNext ()
ptr_psi_term intListValue (ptr_int_list p)
GENERIC intListNext (ptr_int_list p)
ptr_psi_term quotedStackCopy (psi_term p)
ptr_psi_term residListGoalQuote (ptr_residuation p)
GENERIC residListNext (ptr_residuation p)
ptr_psi_term makePsiTerm (ptr_definition x)
ptr_psi_term makePsiList (GENERIC head, ptr_psi_term(*valueFunc)(), GENERIC(*nextFunc)())
static long c_residList ()
ptr_goal makeGoal (ptr_psi_term p)
static long c_residuate ()
static long c_mresiduate ()
void insert_system_builtins ()
Variables
static GENERIC unitListElement
Macro Definition Documentation
#define copyPsiTerm (a, b) (ptr_psi_term)memcpy(a,b,sizeof(psi_term))
Definition at line 8 of file bi_sys.c.
Function Documentation
static long c_cputime () static
Definition at line 175 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_goal::bbbb_1, deref_args, deref_ptr, get_real_value(), life_end, REAL, set_empty, and unify_real_result().
 {
   ptr_psi_term result, t;
   REAL thetime,val;
   long num,success;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   result=aim->bbbb_1;
   deref_ptr(result);
   success=get_real_value(result,&val,&num);
   if (success) {
     (void)times(&life_end);
     thetime=(life_end.tms_utime-life_start.tms_utime)/60.0;
     if (num)
       success=(val==thetime);
     else
       success=unify_real_result(result,thetime);
   }
   return success;
 }
static long c_encode () static
Definition at line 395 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, encode_types(), set_empty, and TRUE.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   encode_types();
   return TRUE;
 }
static long c_garbage () static
Definition at line 299 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, garbage(), set_empty, and TRUE.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   garbage();
   return TRUE;
 }
static long c_getenv () static
Definition at line 313 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_psi_term::attr_list, wl_goal::bbbb_1, deref_ptr, Errorline(), FALSE, get_two_args(), heap_copy_string(), matches(), NULL, push_goal(), quoted_string, stack_psi_term(), TRUE, wl_psi_term::type, unify, and wl_psi_term::value_3.
 {
   long success=FALSE;
   ptr_psi_term arg1,arg2,funct,result,t;
   long smaller;
   char * s;
   funct = aim->aaaa_1;
   result=aim->bbbb_1;
   deref_ptr(funct);
   deref_ptr(result);
   get_two_args(funct->attr_list, &arg1, &arg2);
   if(arg1) {
     deref_ptr(arg1);
     if(matches(arg1->type,quoted_string,&smaller) && arg1->value_3) {
       s=getenv((char *)arg1->value_3);
       if(s) {
     success=TRUE;
     t=stack_psi_term(4);
     t->type=quoted_string;
     t->value_3=(GENERIC)heap_copy_string(s);
     push_goal(unify,result,t,NULL);
       }
     }
     else
       Errorline("bad argument in %P\n",funct);
   }
   else
     Errorline("argument missing in %P\n",funct);
   return success;
 }
static long c_localtime () static
Definition at line 231 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_goal::bbbb_1, day_attr, deref_args, deref_ptr, hour_attr, minute_attr, month_attr, NULL, push_goal(), second_attr, set_empty, stack_add_int_attr(), stack_psi_term(), timesym, TRUE, wl_psi_term::type, unify, weekday_attr, and year_attr.
 {
   ptr_psi_term result, t, psitime;
   long success=TRUE;
   struct timeval tp;
   struct timezone tzp;
   struct tm *thetime;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   result=aim->bbbb_1;
   deref_ptr(result);
   gettimeofday(&tp, &tzp);
   thetime=localtime((time_t *) &(tp.tv_sec));
   psitime=stack_psi_term(4);
   psitime->type=timesym;
   stack_add_int_attr(psitime, year_attr,    thetime->tm_year+1900);
   stack_add_int_attr(psitime, month_attr,   thetime->tm_mon+1);
   stack_add_int_attr(psitime, day_attr,     thetime->tm_mday);
   stack_add_int_attr(psitime, hour_attr,    thetime->tm_hour);
   stack_add_int_attr(psitime, minute_attr,  thetime->tm_min);
   stack_add_int_attr(psitime, second_attr,  thetime->tm_sec);
   stack_add_int_attr(psitime, weekday_attr, thetime->tm_wday);
   push_goal(unify,result,psitime,NULL);
   return success;
 }
static long c_maxint () static
Definition at line 129 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_goal::bbbb_1, deref_args, deref_ptr, get_real_value(), REAL, set_empty, unify_real_result(), and WL_MAXINT.
 {
   ptr_psi_term t,result;
   REAL val;
   long num,success;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   result=aim->bbbb_1;
   deref_ptr(result);
   success=get_real_value(result,&val,&num);
   if (success) {
     if (num)
       success=(val==(REAL)WL_MAXINT);
     else
       success=unify_real_result(result,(REAL)WL_MAXINT);
   }
   return success;
 }
static long c_mresiduate () static
Definition at line 581 of file bi_sys.c.
References wl_goal::aaaa_1, aim, alist, wl_psi_term::attr_list, deref_args, deref_ptr, Errorline(), FALSE, get_two_args(), makeGoal(), nil, NULL, residuateGoalOnVar(), set_1_2, TRUE, and wl_psi_term::type.
 {
   long success=TRUE;
   ptr_psi_term pred;
   ptr_psi_term arg1, arg2, tmp, var;
   ptr_goal g;
   pred = aim->aaaa_1;
   deref_ptr(pred);
   get_two_args(pred->attr_list, &arg1, &arg2);
   if ((!arg1)||(!arg2)) {
     Errorline("%P requires two arguments.\n",pred);
     return FALSE;
   }
   deref_ptr(arg1);
   deref_ptr(arg2);
   deref_args(pred, set_1_2);
   g = makeGoal(arg2);
   /* Then residuate on all the list variables: */
   tmp=arg1;
   while(tmp && tmp->type==alist) { /*  RM: Dec 14 1992  */
     get_two_args(tmp->attr_list,&var,&tmp);
     if(var) {
       deref_ptr(var);
       (void)residuateGoalOnVar(g,var,NULL);
     }
     if(tmp)
       deref_ptr(tmp);
   }
   if(!tmp || tmp->type!=nil) {
     Errorline("%P should be a nil-terminated list in mresiduate.\n",arg1);
     success=FALSE;
   }
   return success;
 }
long c_quiet ()
Definition at line 155 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_goal::bbbb_1, deref_args, deref_ptr, lf_false, lf_true, NOTQUIET, NULL, push_goal(), set_empty, stack_psi_term(), TRUE, wl_psi_term::type, and unify.
 {
   ptr_psi_term t,result,ans;
   long success=TRUE;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   result=aim->bbbb_1;
   deref_ptr(result);
   ans=stack_psi_term(4);
   ans->type = NOTQUIET ? lf_false : lf_true;
   push_goal(unify,result,ans,NULL);
   return success;
 }
static long c_realtime () static
Definition at line 201 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_goal::bbbb_1, deref_args, deref_ptr, get_real_value(), REAL, set_empty, and unify_real_result().
 {
   ptr_psi_term result, t;
   REAL thetime,val;
   long num,success;
   struct timeval tp;
   struct timezone tzp;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   result=aim->bbbb_1;
   deref_ptr(result);
   success=get_real_value(result,&val,&num);
   if (success) {
     gettimeofday(&tp, &tzp);
     thetime=(REAL)tp.tv_sec + ((REAL)tp.tv_usec/1000000.0);
     /* thetime=times(&life_end)/60.0; */
     if (num)
       success=(val==thetime);
     else
       success=unify_real_result(result,thetime);
   }
   return success;
 }
static long c_residList () static
Definition at line 504 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_psi_term::attr_list, wl_goal::bbbb_1, curry(), deref, deref_args, deref_ptr, get_one_arg(), makePsiList(), NULL, push_goal(), wl_psi_term::resid, resid_aim, residListGoalQuote(), residListNext(), set_1, TRUE, and unify.
 {
   ptr_psi_term func;
   ptr_psi_term result,arg1, other;
   func = aim->aaaa_1;
   deref_ptr(func);
   get_one_arg(func->attr_list, &arg1);
   if (!arg1)
     {
       curry();
       return TRUE;
     }
   result = aim->bbbb_1;
   deref(result);
   deref_ptr(arg1);
   deref_args(func, set_1);
   other = makePsiList((void *)arg1->resid,
               residListGoalQuote,
               residListNext);
   resid_aim = NULL;
   push_goal(unify,result,other,NULL);
   return TRUE;
 }
static long c_residuate () static
Definition at line 550 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_psi_term::attr_list, deref_args, deref_ptr, Errorline(), FALSE, get_two_args(), makeGoal(), NULL, residuateGoalOnVar(), set_1_2, and TRUE.
 {
   ptr_psi_term pred;
   ptr_psi_term arg1, arg2;
   ptr_goal g;
   pred = aim->aaaa_1;
   deref_ptr(pred);
   get_two_args(pred->attr_list, &arg1, &arg2);
   if ((!arg1)||(!arg2)) {
     Errorline("%P requires two arguments.\n",pred);
     return FALSE;
   }
   deref_ptr(arg1);
   deref_ptr(arg2);
   deref_args(pred, set_1_2);
   g = makeGoal(arg2);
   (void)residuateGoalOnVar(g, arg1, NULL);
   return TRUE;
 }
static long c_statistics () static
Definition at line 265 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, heap_pointer, mem_base, mem_limit, set_empty, stack_pointer, and TRUE.
 {
   ptr_psi_term t;
   long success=TRUE;
   long t1,t2,t3;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   t1 = sizeof(mem_base)*(stack_pointer-mem_base);
   t2 = sizeof(mem_base)*(mem_limit-heap_pointer);
   t3 = sizeof(mem_base)*(mem_limit-mem_base);
   printf("\n");
   /* printf("************** SYSTEM< INFORMATION **************\n"); */
   printf("Stack size  : %8ld bytes (%5ldK) (%ld%%)\n",t1,t1/1024,100*t1/t3);
   printf("Heap size   : %8ld bytes (%5ldK) (%ld%%)\n",t2,t2/1024,100*t2/t3);
   printf("Total memory: %8ld bytes (%5ldK)\n",t3,t3/1024);
 #ifdef X11
   printf("X predicates are installed.\n");
 #else
   printf("X predicates are not installed.\n");
 #endif
   /* printf("\n"); */
   /* printf("************************************************\n"); */
   return success;
 }
static long c_step () static
Definition at line 79 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, set_empty, toggle_step(), and TRUE.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   toggle_step();
   return TRUE;
 }
static long c_system () static
Definition at line 349 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_psi_term::attr_list, wl_goal::bbbb_1, curry(), deref, deref_args, deref_ptr, Errorline(), FALSE, get_two_args(), matches(), quoted_string, REAL, set_1, TRUE, wl_psi_term::type, unify_real_result(), and wl_psi_term::value_3.
 {
   long success=TRUE;
   ptr_psi_term arg1,arg2,funct,result;
   REAL value;
   long smaller;
   funct=aim->aaaa_1;
   deref_ptr(funct);
   result=aim->bbbb_1;
   get_two_args(funct->attr_list,&arg1,&arg2);
   if(arg1) {
     deref(arg1);
     deref_args(funct,set_1);
     if((success=matches(arg1->type,quoted_string,&smaller)))
       if(arg1->value_3) {
     value=(REAL)system((char *)arg1->value_3);
     if(value==127) {
       success=FALSE;
           Errorline("could not execute shell in %P.\n",funct);
       /* report_error(funct,"couldn't execute shell"); */
     }
     else
       success=unify_real_result(result,value);
       }
       else {
     /* residuate(arg1); */ /*  RM: Feb 10 1993  */
         success=FALSE;
         Errorline("bad argument in %P.\n",funct);
       }
     else {
       success=FALSE;
       Errorline("bad argument in %P.\n",funct);
       /* report_error(funct,"bad argument"); */
     }
   }
   else
     curry();
   return success;
 }
long c_tprove ()
Definition at line 65 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, set_empty, set_trace_to_prove(), and TRUE.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   set_trace_to_prove();
   return TRUE;
 }
long c_trace ()
Definition at line 20 of file bi_sys.c.
References wl_goal::aaaa_1, aim, wl_psi_term::attr_list, deref_args, deref_ptr, Errorline(), FALSE, get_two_args(), is_top, lf_false, lf_true, set_empty, stepflag, toggle_trace(), trace, TRUE, wl_psi_term::type, and unify_bool_result().
 {
   long success=TRUE;
   ptr_psi_term t,arg1,arg2;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   get_two_args(t->attr_list,&arg1,&arg2);
   if (arg1) {
     deref_ptr(arg1);
     if (is_top(arg1)) {
       unify_bool_result(arg1,trace);
       trace=FALSE;
     }
     else if (arg1->type==lf_true)
       trace=TRUE;
     else if (arg1->type==lf_false)
       trace=FALSE;
     else {
       Errorline("bad first argument in %P.\n",t);
       /* report_error(t,"bad first argument"); */
       success=FALSE;
     }
   }
   if (arg2) {
     deref_ptr(arg2);
     if (is_top(arg2)) {
       unify_bool_result(arg2,stepflag);
       stepflag=FALSE;
     }
     else if (arg2->type==lf_true)
       stepflag=TRUE;
     else if (arg2->type==lf_false)
       stepflag=FALSE;
     else {
       Errorline("bad second argument in %P.\n",t);
       /* report_error(t,"bad second argument"); */
       success=FALSE;
     }
   }
   if (!arg1 && !arg2)
     toggle_trace();
   return success;
 }
static long c_verbose () static
Definition at line 93 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, set_empty, TRUE, and verbose.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   verbose = !verbose;
   printf("*** Verbose mode is turned ");
   printf(verbose?"on.\n":"off.\n");
   return TRUE;
 }
static long c_warning () static
Definition at line 111 of file bi_sys.c.
References wl_goal::aaaa_1, aim, deref_args, infoline(), set_empty, TRUE, and warningflag.
 {
   ptr_psi_term t;
   t=aim->aaaa_1;
   deref_args(t,set_empty);
   warningflag = !warningflag;
   /*  RM: Sep 24 1993  */
   infoline("*** Warning messages are%s printed\n",warningflag?"":" not");
   return TRUE;
 }
void insert_system_builtins ()
Definition at line 626 of file bi_sys.c.
References bi_module, c_cputime(), c_encode(), c_garbage(), c_getenv(), c_localtime(), c_maxint(), c_mresiduate(), c_quiet(), c_realtime(), c_residList(), c_residuate(), c_statistics(), c_step(), c_system(), c_tprove(), c_trace(), c_verbose(), c_warning(), function_it, new_built_in(), and predicate.
 {
   new_built_in(bi_module,"trace",(def_type)predicate,c_trace);
   new_built_in(bi_module,"step",(def_type)predicate,c_step);
   new_built_in(bi_module,"verbose",(def_type)predicate,c_verbose);
   new_built_in(bi_module,"warning",(def_type)predicate,c_warning);
   new_built_in(bi_module,"maxint",(def_type)function_it,c_maxint);
   new_built_in(bi_module,"cpu_time",(def_type)function_it,c_cputime);
   new_built_in(bi_module,"quiet",(def_type)function_it,c_quiet); /* 21.1 */
   new_built_in(bi_module,"real_time",(def_type)function_it,c_realtime);
   new_built_in(bi_module,"local_time",(def_type)function_it,c_localtime);
   new_built_in(bi_module,"statistics",(def_type)predicate,c_statistics);
   new_built_in(bi_module,"gc",(def_type)predicate,c_garbage);
   new_built_in(bi_module,"system",(def_type)function_it,c_system);
   new_built_in(bi_module,"getenv",(def_type)function_it,c_getenv);
   new_built_in(bi_module,"encode",(def_type)predicate,c_encode);
   new_built_in(bi_module,"rlist",(def_type)function_it,c_residList);
   new_built_in(bi_module,"residuate",(def_type)predicate,c_residuate);
   new_built_in(bi_module,"mresiduate",(def_type)predicate,c_mresiduate);
   new_built_in(bi_module,"tprove",(def_type)predicate,c_tprove);
 }
GENERIC intListNext (ptr_int_list p)
Definition at line 430 of file bi_sys.c.
 {
   return (GENERIC )(p->next);
 }
ptr_psi_term intListValue (ptr_int_list p)
Definition at line 424 of file bi_sys.c.
References makePsiTerm().
 {
   return makePsiTerm((void *)p->value_1);
 }
ptr_goal makeGoal (ptr_psi_term p)
Definition at line 533 of file bi_sys.c.
References DEFRULES, goal_stack, wl_goal::next, NULL, prove, and push_goal().
 {
   ptr_goal old = goal_stack;
   ptr_goal g;
   push_goal(prove, p,(ptr_psi_term) DEFRULES,(GENERIC) NULL);
   g = goal_stack;
   g->next=NULL;
   goal_stack = old;
   return g;
 }
ptr_psi_term makePsiList (GENERIC head, ptr_psi_term (*)() valueFunc, GENERIC (*)() nextFunc)
Definition at line 480 of file bi_sys.c.
References stack_cons(), and stack_nil().
 {
   ptr_psi_term result;
   /*  RM: Dec 14 1992: Added the new list representation  */
   result=stack_nil();
   while (head) {
     result=stack_cons((*valueFunc)(head),result);
     head=(*nextFunc)(head);
   }
   return result;
 }
ptr_psi_term makePsiTerm (ptr_definition x)
Definition at line 468 of file bi_sys.c.
References stack_psi_term(), and wl_psi_term::type.
 {
   ptr_psi_term p;
   p = stack_psi_term(4);
   p->type = x;
   return p;
 }
ptr_psi_term quotedStackCopy (psi_term p)
Definition at line 436 of file bi_sys.c.
References mark_quote(), and stack_copy_psi_term().
 {
   ptr_psi_term q;
   q = (ptr_psi_term) stack_copy_psi_term(p);
   mark_quote(q);
   return q;
 }
ptr_psi_term residListGoalQuote (ptr_residuation p)
Definition at line 451 of file bi_sys.c.
References copyPsiTerm, stack_psi_term(), and wl_psi_term::status.
 {
   ptr_psi_term psi;
   psi = stack_psi_term(4);
   copyPsiTerm(psi, p->goal->aaaa_1);
   psi->status =  4;
   return psi;
 }
GENERIC residListNext (ptr_residuation p)
Definition at line 462 of file bi_sys.c.
 {
   return (GENERIC )(p->next);
 }
void setUnitList (GENERIC x)
Definition at line 407 of file bi_sys.c.
References unitListElement.
 {
   unitListElement = x;
 }
GENERIC unitListNext ()
Definition at line 418 of file bi_sys.c.
References NULL, and unitListElement.
 {
   unitListElement = NULL;
   return NULL;
 }
ptr_psi_term unitListValue ()
Definition at line 413 of file bi_sys.c.
References makePsiTerm(), and unitListElement.
 {
   return makePsiTerm((void *)unitListElement);
 }
Variable Documentation
GENERIC unitListElement static
Definition at line 405 of file bi_sys.c.