Wild Life: life.c File Reference
life.c File Reference
Functions
int main (int argc, char *argv[])
Variables
char * numbers [21]
long set_extra_args [6] = {set_empty, set_1, set_2, set_1_2, set_1_2_3, set_1_2_3_4}
Function Documentation
int main (int argc, char * argv[])
Definition at line 40 of file life.c.
References arg_c, arg_v, assert, assert_clause(), assert_first, assert_ok, begin_terminal_io(), DEFRULES, encode_types(), end_terminal_io(), env, eof, Errorline(), exit_if_true(), exit_life(), FACT, FALSE, file_date, GetBoolOption(), goal_count, heap_copy_string(), ignore_eff, infoline(), init_built_in_types(), init_copy(), init_interrupt(), init_io(), init_memory(), init_modules(), init_print(), init_system(), init_trace(), input_state, load, main_prove(), mem_base, noisy, NULL, open_input_file(), other_base, parse(), prove, push_goal(), put_back_char(), QUERY, quietflag, rand_array, read_char(), reset_step(), set_current_module(), stack_copy_psi_term(), stack_pointer, start_chrono(), stdin_cleareof(), title(), TRUE, wl_psi_term::type, undo(), undo_stack, user_module, var_occurred, and what_next.
 {
   ptr_psi_term s;
   ptr_stack save_undo_stack;
   long sort,exitflag;
   long c; /* 21.12 (prev. char) */
   int i;
 #ifdef SOLARIS
   for(i=0;i<256;i++)
     rand_array[i]=rand_r(&lifeseed);
 #else
   for(i=0;i<256;i++)
     rand_array[i]=random();
 #endif
   arg_c=argc;
   if (argc < 10)
     {
       for (i = 0; i < argc;i++)
     {
       arg_v[i]=argv[i];
     }
     }
   else
     Errorline("Too many command line arguments\n");
   //  arg_v=argv;
   quietflag = GetBoolOption("q");
   init_io();
   init_memory();
   exit_if_true(!mem_base || !other_base);
   assert(stack_pointer==mem_base); /* 8.10 */
   init_copy();
   assert(stack_pointer==mem_base); /* 8.10 */
   init_print();
   assert(stack_pointer==mem_base); /* 8.10 */
   /* Timekeeping initialization */
   tzset();
   (void)times(&life_start);
   assert(stack_pointer==mem_base); /* 8.10 */
   init_modules(); /*  RM: Jan  8 1993  */
   init_built_in_types();
   assert(stack_pointer==mem_base); /* 8.10 */
 #ifdef X11
   x_setup_builtins();
   assert(stack_pointer==mem_base); /* 8.10 */
 #endif
   init_interrupt();
   assert(stack_pointer==mem_base); /* 8.10 */
   title();
   assert(stack_pointer==mem_base); /* 8.10 */
   init_trace();
   noisy=FALSE;
   assert(stack_pointer==mem_base); /* 8.10 */
   (void)set_current_module(user_module); /*  RM: Jan 27 1993  */
   /* Read in the .set_up file */
   init_system();
 #ifdef ARITY  /*  RM: Mar 29 1993  */
   arity_init();
 #endif
   (void)open_input_file("+SETUP+");
   push_goal(load,input_state,(ptr_psi_term)file_date,(GENERIC)heap_copy_string("+SETUP+"));
   file_date+=2;
   main_prove();
   /* Main loop of interpreter */
   do {
     (void)setjmp(env);
     /* printf("%ld\n",(long)(stack_pointer-mem_base)); */ /* 8.10 */
     init_system();
     init_trace();
     begin_terminal_io();
     var_occurred=FALSE;
     save_undo_stack=undo_stack;
     stdin_cleareof();
     c=read_char();
     /* Wait until an EOF or a good character */
     while (c!=EOF && !(c>32 && c!='.' && c!=';')) c=read_char();
     if (c==EOF)
       exitflag=TRUE;
     else {
       put_back_char(c);
       s=stack_copy_psi_term(parse(&sort));
       exitflag=(s->type==eof);
     }
     end_terminal_io();
     if (!exitflag) {
       if (sort==QUERY) {
     // clear_already_loaded(symbol_table);     RM: Feb  3 1993
         push_goal(what_next,(ptr_psi_term)TRUE,(ptr_psi_term)var_occurred,(GENERIC)1);
         ignore_eff=TRUE;
         goal_count=0;
         push_goal(prove,s,(ptr_psi_term)DEFRULES,NULL);
         reset_step();
         start_chrono();
         main_prove();
         /* assert(goal_stack==NULL); */
         /* assert(choice_stack==NULL); */
     if (undo_stack) {
       undo(NULL);
           Errorline("non-NULL undo stack.\n");
     }
         /* assert(undo_stack==NULL); */
       }
       else if (sort==FACT) {
         assert_first=FALSE;
         assert_clause(s);
         undo(save_undo_stack); /* 17.8 */
         var_occurred=FALSE; /* 18.8 */
         encode_types();
         infoline(assert_ok?"\n*** Yes\n":"\n*** No\n"); /* 21.1 */
      }
     }
   } while (!exitflag);
   /* hash_display(x_module->symbol_table); */
   exit_life(TRUE);
   return 0;
 }
Variable Documentation
char* numbers[21]
Initial value:
= {"1","2","3","4","5","6","7","8","9","10",
           "11","12","13","14","15","16","17","18","19","20",
           NULL}
Definition at line 13 of file life.c.
long set_extra_args[6] = {set_empty, set_1, set_2, set_1_2, set_1_2_3, set_1_2_3_4}
Definition at line 18 of file life.c.