Wild Life: list.c File Reference
list.c File Reference
Functions
void List_SetLinkProc (RefListHeader header, RefListGetLinksProc getLinks)
void List_InsertAhead (RefListHeader header, Ref atom)
void List_Append (RefListHeader header, Ref atom)
void List_InsertBefore (RefListHeader header, Ref atom, Ref mark)
void List_InsertAfter (RefListHeader header, Ref atom, Ref mark)
void List_Swap (RefListHeader header, Ref first, Ref second)
static long List_SwapLinks (RefListHeader header, Ref atom)
void List_Reverse (RefListHeader header)
void List_Remove (RefListHeader header, Ref atom)
void List_Concat (RefListHeader header1, RefListHeader header2)
long List_EnumFrom (RefListHeader header, Ref atom, RefListEnumProc proc, Ref closure)
long List_Enum (RefListHeader header, RefListEnumProc proc, Ref closure)
long List_EnumBackFrom (RefListHeader header, Ref atom, RefListEnumProc proc, Ref closure)
long List_EnumBack (RefListHeader header, RefListEnumProc proc, Ref closure)
static long List_CountAtom (Ref p, Ref nbR)
long List_Card (RefListHeader header)
long List_IsUnlink (RefListLinks links)
void List_Cut (RefListHeader header, Ref atom, RefListHeader newHeader)
Function Documentation
void List_Append (RefListHeader header, Ref atom)
Definition at line 63 of file list.c.
References NULL.
 {
     RefListGetLinksProc  getLinks = header->GetLinks;
             /* Link to the end of list */
     if (header->Last != NULL)
       (*getLinks)(header->Last)->Next = atom;
     else    /* The list is empty */
       header->First = atom;
             /* Update links of atom to insert */
     (*getLinks)(atom)->Prev = header->Last;
     (*getLinks)(atom)->Next = NULL;
         /* Update last element of header */
     header->Last  = atom;
 }
long List_Card (RefListHeader header)
Definition at line 410 of file list.c.
References List_CountAtom(), and List_Enum().
 {
     long n = 0;
     (void)List_Enum (header,(RefListEnumProc) List_CountAtom, &n);
     return n;
 }
void List_Concat (RefListHeader header1, RefListHeader header2)
Definition at line 277 of file list.c.
References wl_ListHeader::First, wl_ListHeader::GetLinks, wl_ListHeader::Last, and NULL.
 {
     RefListGetLinksProc  getLinks = header1->GetLinks;
     if (header1->GetLinks == header2->GetLinks)
     {
 #ifdef prlDEBUG
     OS_PrintMessage ("List_Concat: ERROR concat different lists\n");
 #endif
     return;
     }
     /* Concatenate only if the second list is not empty */
     if (header2->First != NULL)
     {
     /* Obvious concatenate when the first list is empty */
         if (header1->First == NULL)
             header1->First = header2->First;
         else    /* Concatenate the two non empty lists */
         {
             (*getLinks)(header1->Last)->Next  = header2->First;
             (*getLinks)(header2->First)->Prev = header1->Last;
         }
         header1->Last = header2->Last;
     }
 }
static long List_CountAtom (Ref p, Ref nbR) static
Definition at line 400 of file list.c.
References TRUE.
 {
     long *nb = (long *)nbR;
     ++*nb;
     return TRUE;
 }
void List_Cut (RefListHeader header, Ref atom, RefListHeader newHeader)
Definition at line 429 of file list.c.
References wl_ListHeader::First, wl_ListHeader::Last, List_Last, List_Next, and NULL.
 {
     RefListGetLinksProc  getLinks = header->GetLinks;
     if (atom != List_Last (header))
     {
     newHeader->First = List_Next (header, atom);
     newHeader->Last  = header->Last;
     header->Last = atom;
     /* Update the links */
     (*getLinks)(atom)->Next = NULL;
     (*getLinks)(newHeader->First)->Prev = NULL;
     }
 }
long List_Enum (RefListHeader header, RefListEnumProc proc, Ref closure)
Definition at line 341 of file list.c.
References List_EnumFrom().
 {
     return (List_EnumFrom (header, header->First, proc, closure));
 }
long List_EnumBack (RefListHeader header, RefListEnumProc proc, Ref closure)
Definition at line 389 of file list.c.
References List_EnumBackFrom().
 {
     return (List_EnumBackFrom (header, header->Last, proc, closure));
 }
long List_EnumBackFrom (RefListHeader header, Ref atom, RefListEnumProc proc, Ref closure)
Definition at line 359 of file list.c.
References List_Prev, NULL, and TRUE.
 {
     Ref cur, prev;
     int notInterrupted = TRUE;
 #ifdef prlDEBUG
     header->Lock += 1;
 #endif
     cur = atom;
     while (cur != NULL && notInterrupted)
     {
     prev = List_Prev (header, cur);
     notInterrupted = (*proc)(cur, closure);
     cur = prev;
     }
 #ifdef prlDEBUG
     header->Lock -=1;
 #endif
     return (notInterrupted);
 }
long List_EnumFrom (RefListHeader header, Ref atom, RefListEnumProc proc, Ref closure)
Definition at line 311 of file list.c.
References List_Next, NULL, and TRUE.
 {
     Ref cur, next;
     int notInterrupted = TRUE;
 #ifdef prlDEBUG
     header->Lock += 1;
 #endif
     cur = atom;
     while (cur != NULL && notInterrupted)
     {
     next = List_Next (header, cur);
     notInterrupted = (*proc)(cur, closure);
     cur = next;
     }
 #ifdef prlDEBUG
     header->Lock -=1;
 #endif
     return (notInterrupted);
 }
void List_InsertAfter (RefListHeader header, Ref atom, Ref mark)
Definition at line 119 of file list.c.
References List_InsertAhead(), and NULL.
 {
     RefListGetLinksProc  getLinks = header->GetLinks;
 #ifdef prlDEBUG
     if (header->Lock > 1)
       OS_PrintMessage ("List_InsertAfter: Warning insert after on recursive List_Enum call !!\n");
 #endif
     if (mark != NULL)
     {
         (*getLinks)(atom)->Prev = mark;
         if (mark != header->Last)
         {
             (*getLinks)(atom)->Next = (*getLinks)(mark)->Next;
             (*getLinks)((*getLinks)(mark)->Next)->Prev = atom;
         }
         else    /* Insert at the end of the list */
         {
             (*getLinks)(atom)->Next = NULL;
             header->Last = atom;
         }
         (*getLinks)(mark)->Next = atom;
     }
     else        /* Insert ahead the list */
       List_InsertAhead (header, atom);
 }
void List_InsertAhead (RefListHeader header, Ref atom)
Definition at line 39 of file list.c.
References NULL.
 {
     RefListGetLinksProc  getLinks = header->GetLinks;
         /* Update links of atom to insert */
     (*getLinks)(atom)->Next = header->First;
     (*getLinks)(atom)->Prev = NULL;
         /* Link to the head of list */
     if (header->First != NULL)
       (*getLinks)(header->First)->Prev = atom;
     else    /* The list is empty */
       header->Last  = atom;
     header->First = atom;
 }
void List_InsertBefore (RefListHeader header, Ref atom, Ref mark)
Definition at line 89 of file list.c.
References List_Append(), wl_ListLinks::Next, and NULL.
 {
     RefListGetLinksProc  getLinks = header->GetLinks;
     if (mark != NULL)
     {
         (*getLinks)(atom)->Next = mark;
         if (mark != header->First)
         {
             (*getLinks)(atom)->Prev = (*getLinks)(mark)->Prev;
             (*getLinks)((*getLinks)(mark)->Prev)->Next = atom;
         }
         else    /* Insert ahead the list */
         {
             (*getLinks)(atom)->Prev = NULL;
             header->First = atom;
         }
         (*getLinks)(mark)->Prev = atom;
     }
     else        /* Append to the list */
       List_Append (header, atom);
 }
long List_IsUnlink (RefListLinks links)
Definition at line 421 of file list.c.
References NULL.
 {
     return (links->Next == NULL && links->Prev == NULL);
 }
void List_Remove (RefListHeader header, Ref atom)
Definition at line 230 of file list.c.
References NULL.
 {
 /*-----------------------------------------------------------------------------
 WARNING
     - The container is 'updated' two times if the first and last atom
       of list is the only one to remove.
 -----------------------------------------------------------------------------*/
     RefListGetLinksProc  getLinks = header->GetLinks;
 #ifdef prlDEBUG
     if (header->Lock > 1)
       OS_PrintMessage ("List_Remove: Warning remove on recursive List_Enum call !!\n");
 #endif
         /* Update the DownStream links */
     if ((*getLinks)(atom)->Prev != NULL)
     {
         (*getLinks)((*getLinks)(atom)->Prev)->Next =
             (*getLinks)(atom)->Next;
     }
     else            /* Atom is the first of list */
       header->First = (*getLinks)(atom)->Next;
         /* Update the UpStream links */
     if ((*getLinks)(atom)->Next != NULL)
     {
         (*getLinks)((*getLinks)(atom)->Next)->Prev =
             (*getLinks)(atom)->Prev;
     }
     else            /* Atom is the last of list */
       header->Last = (*getLinks)(atom)->Prev;
         /* Reset the atom links */
     (*getLinks)(atom)->Prev = NULL;
     (*getLinks)(atom)->Next = NULL;
 }
void List_Reverse (RefListHeader header)
Definition at line 206 of file list.c.
References List_SwapLinks(), and NULL.
 {
     Ref         cur, next;
     RefListGetLinksProc getLinks = header->GetLinks;
     /* This traverse cannot be done with function List_Enum() */
     cur = header->First;
     /* Swap the headers */
     header->First = header->Last;
     header->Last  = cur;
     while (cur != NULL)
     {
     next = (*getLinks)(cur)->Next;
     (void)List_SwapLinks (header, cur);
     cur = next;
     }
 }
void List_SetLinkProc (RefListHeader header, RefListGetLinksProc getLinks)
Definition at line 21 of file list.c.
References NULL.
 {
     header->First = NULL;
     header->Last = NULL;
 #ifdef prlDEBUG
     header->Lock = 0;
 #endif
     header->GetLinks = getLinks;
 }
void List_Swap (RefListHeader header, Ref first, Ref second)
Definition at line 154 of file list.c.
 {
     RefListGetLinksProc getLinks = header->GetLinks;
     /* Don't swap if the input is wrong */
     if ((*getLinks)(first)->Next != second)
     {
 #ifdef prlDEBUG
     OS_PrintMessage ("List_Swap: WARNING wrong input data, swap not done..\n");
 #endif
     return;
     }
         /* Special Cases */
     if (header->First == first)
       header->First = second;
     else
       (*getLinks)((*getLinks)(first)->Prev)->Next = second;
     if (header->Last == second)
       header->Last = first;
     else
       (*getLinks)((*getLinks)(second)->Next)->Prev = first;
         /* Swap the atoms */
     (*getLinks)(second)->Prev = (*getLinks)(first)->Prev;
     (*getLinks)(first)->Next  = (*getLinks)(second)->Next;
     (*getLinks)(first)->Prev  = second;
     (*getLinks)(second)->Next = first;
 }
static long List_SwapLinks (RefListHeader header, Ref atom) static
Definition at line 193 of file list.c.
References TRUE.
 {
     Ref save;
     save = (*header->GetLinks)(atom)->Next;
     (*header->GetLinks)(atom)->Next = (*header->GetLinks)(atom)->Prev;
     (*header->GetLinks)(atom)->Prev = save;
     return TRUE;
 }