#! /bin/csh -f
# Script to visualize the differences between the reference and test runs.
# Uses "dxdiff" which is a DEC proprietary X interface to diff.
# You can try replacing it with "sdiff" on SUNs.

foreach I ($*)
	dxdiff REFOUT/$I:r.refout OUT/$I:r.out
	dxdiff REFERR/$I:r.referr ERR/$I:r.err
end
