#!/bin/csh

set DIR = `pwd`

% setenv SLDIR /udir/venet/LIFE/SUPERLINT/PACKAGE
setenv SLDIR ~/life_local_redo/Examples/SuperLint

chdir $SLDIR

~/bin/wild_life -q $DIR slc.lf $* <<EOF

[@, "-q", Directory, Binary | Args] = argv,
  load(Binary),
    wl_main(Directory, Args),
      halt ?
EOF
