#!/bin/csh -f
# Test program for Wild-LIFE
# Runs the entire test-suite and generates a log file
set umask=666
rm -f editdiffs.sh
touch editdiffs.sh
chmod u+x editdiffs.sh
if (! -d "ERR" ) then 
    mkdir ERR
endif
if (! -d "OUT" ) then 
    mkdir OUT
endif
if (! -d "ERRDIFF" ) then 
    mkdir ERRDIFF
endif
if (! -d "REFDIFF" ) then 
    mkdir REFDIFF
endif
rm LF-X/*~
if ($1 == 1) then
echo "Running complete Test"
./check_edit-X `ls LF-X` | tee editdiffs.sh
else 
echo "Testing $1 - $2 only! "
rm LFTMP/*.lf
touch LFTMP-X/$2.lf
./check_edit-X `ls LFTMP-X`
echo "$2 Tested"
endif
chmod u+x editdiffs.sh
