diff ../../Life-1.02/Source/arity.c arity.c >diffs.out 
diff ../../Life-1.02/Source/bi_math.c bi_math.c >>diffs.out 
diff ../../Life-1.02/Source/bi_sys.c bi_sys.c >>diffs.out 
diff ../../Life-1.02/Source/bi_type.c bi_type.c >>diffs.out 
diff ../../Life-1.02/Source/built_ins.c built_ins.c >>diffs.out 
diff ../../Life-1.02/Source/copy.c copy.c >>diffs.out 
diff ../../Life-1.02/Source/error.c error.c >>diffs.out 
diff ../../Life-1.02/Source/hash_table.c hash_table.c >>diffs.out 
diff ../../Life-1.02/Source/info.c info.c >>diffs.out 
diff ../../Life-1.02/Source/interrupt.c interrupt.c >>diffs.out 
diff ../../Life-1.02/Source/lefun.c lefun.c >>diffs.out 
diff ../../Life-1.02/Source/lib.c lib.c >>diffs.out 
diff ../../Life-1.02/Source/life.c life.c >>diffs.out 
diff ../../Life-1.02/Source/list.c list.c >>diffs.out 
diff ../../Life-1.02/Source/login.c login.c >>diffs.out 
diff ../../Life-1.02/Source/lub.c lub.c >>diffs.out 
diff ../../Life-1.02/Source/memory.c memory.c >>diffs.out 
diff ../../Life-1.02/Source/modules.c modules.c >>diffs.out 
diff ../../Life-1.02/Source/parser.c  parser.c >>diffs.out 
diff ../../Life-1.02/Source/print.c  print.c >>diffs.out 
diff ../../Life-1.02/Source/raw.c raw.c >>diffs.out 
diff ../../Life-1.02/Source/sys.c sys.c >>diffs.out 
diff ../../Life-1.02/Source/sys_dbm.c sys_dbm.c >>diffs.out 
diff ../../Life-1.02/Source/templates.c templates.c >>diffs.out 
diff ../../Life-1.02/Source/token.c token.c >>diffs.out 
diff ../../Life-1.02/Source/trees.c trees.c >>diffs.out 
diff ../../Life-1.02/Source/types.c types.c >>diffs.out 
diff ../../Life-1.02/Source/xdisplaylist.c xdisplaylist.c >>diffs.out 
diff ../../Life-1.02/Source/xpred.c xpred.c >>diffs.out 
