diff --ignore-all-space ARITY.C arity.c >diff.out
diff --ignore-all-space BI_MATH.C bi_math.c >>diff.out
diff --ignore-all-space BI_SYS.C bi_sys.c  >>diff.out
diff --ignore-all-space BI_TYPE.C bi_type.c >>diff.out
diff --ignore-all-space BUILT_IN.C built_ins.c >>diff.out
diff --ignore-all-space COPY.C copy.c >>diff.out
diff --ignore-all-space ERROR.C error.c >>diff.out
diff --ignore-all-space HASH_TAB.C hash_table.c  >>diff.out
diff --ignore-all-space INFO.C info.c  >>diff.out
diff --ignore-all-space INTERRUP.C interrupt.c >>diff.out
diff --ignore-all-space LEFUN.C lefun.c >>diff.out
diff --ignore-all-space LIB.C lib.c >>diff.out
diff --ignore-all-space LIFE.C life.c >>diff.out
diff --ignore-all-space LIST.C list.c >>diff.out
diff --ignore-all-space LOGIN.C login.c >>diff.out
diff --ignore-all-space LUB.C lub.c >>diff.out
diff --ignore-all-space MEMORY.C memory.c  >>diff.out
diff --ignore-all-space MODULES.C modules.c >>diff.out
diff --ignore-all-space PARSER.C parser.c >>diff.out
diff --ignore-all-space PRINT.C print.c >>diff.out
diff --ignore-all-space RAW.C raw.c >>diff.out
diff --ignore-all-space SYS.C sys.c >>diff.out
diff --ignore-all-space SYS_DBM.C sys_dbm.c >>diff.out
diff --ignore-all-space TEMPLATE.C templates.c >>diff.out
diff --ignore-all-space TOKEN.C token.c >>diff.out
diff --ignore-all-space TREES.C trees.c >>diff.out
diff --ignore-all-space TYPES.C types.c >>diff.out
diff --ignore-all-space XDISPLAY.C xdisplaylist.c >>diff.out
diff --ignore-all-space XPRED.C xpred.c >>diff.out
emacs diff.out
