echo ./aaa-0000-darland -- Matches Perfectly
echo ./aaa-00-listing -- Matches Perfectly
echo ./aaa-00-module -- Matches Perfectly
echo ./aaa-00-quote -- Matches Perfectly
echo ./aaa-03-03 -- Matches Perfectly
echo ./aaa-04-02 -- Matches Perfectly
echo ./aaa-04-03B -- Matches Perfectly
echo ./aaa-04-03 -- Matches Perfectly
echo ./aaa-05-01 -- Matches Perfectly
echo ./aaa-05-02 -- Matches Perfectly
echo ./aaa-05-04 -- Matches Perfectly
echo ./aaa-06-01 -- Matches Perfectly
echo ./aaa-06-02 -- Matches Perfectly
echo ./aaa-06-03 -- Matches Perfectly
echo ./aaa-06-04 -- Matches Perfectly
echo ./aaa-06-05 -- Matches Perfectly
echo ./aaa-06-06 -- Matches Perfectly
echo ./aaa-06-07 -- Matches Perfectly
echo ./aaa-06-08 -- Matches Perfectly
echo ./aaa-06-09 -- Matches Perfectly
echo ./aaa-06-10 -- Matches Perfectly
echo ./aaa-06-11 -- Matches Perfectly
echo ./aaa-06-12 -- Matches Perfectly
echo ./aaa-06-13 -- Matches Perfectly
echo ./aaa-06-14 -- Matches Perfectly
echo ./aaa-06-15 -- Matches Perfectly
echo ./aaa-06-16 -- Matches Perfectly
echo ./aaa-06-17A -- Matches Perfectly
echo ./aaa-06-17B -- Matches Perfectly
echo ./aaa-06-17C -- Matches Perfectly
echo ./aaa-06-17 -- Matches Perfectly
echo ./aaa-07-01 -- Matches Perfectly
echo ./aaa-07-03 -- Matches Perfectly
echo ./aaa-07-04 -- Matches Perfectly
echo ./aaa-07-05 -- Matches Perfectly
echo ./aaa-07-06 -- Matches Perfectly
echo ./aaa-07-07 -- Matches Perfectly
echo ./aaa-08-02 -- Matches Perfectly
echo ./aaa-08-03 -- Matches Perfectly
echo ./aaa-08-04 -- Matches Perfectly
echo ./aaa-08-05 -- Matches Perfectly
echo ./aaa-08-06 -- Matches Perfectly
echo ./aaa-08-07 -- Matches Perfectly
echo ./aaa-08-08 -- Matches Perfectly
echo ./aaa-08-09 -- Matches Perfectly
echo ./aaa-08-10 -- Matches Perfectly
echo ./aaa-08-11 -- Matches Perfectly
echo ./aaa-08-12 -- Matches Perfectly
echo ./aaa-08-13 -- Matches Perfectly
echo ./aaa-08-14-arith-64 -- Matches Perfectly
echo ./aaa-08-14-arith -- Matches Perfectly
echo ./aaa-08-14-bool -- Matches Perfectly
echo ./aaa-08-14 -- Matches Perfectly
echo ./aaa-08-14-neg -- Matches Perfectly
echo ./aaa-08-15 -- Matches Perfectly
echo ./aaa-08-16 -- Matches Perfectly
echo ./aaa-08-17 -- Matches Perfectly
echo ./aaa-08-18 -- Matches Perfectly
echo ./aaa-08-19 -- Matches Perfectly
echo ./aaa-08-20 -- Matches Perfectly
echo ./aaa-08-21 -- Matches Perfectly
echo ./aaa-08-22 -- Matches Perfectly
echo ./aaa-08-23 -- Matches Perfectly
echo ./aaa-08-24 -- Matches Perfectly
echo ./aaa-08-25 -- Matches Perfectly
echo ./aaa-08-26 -- Matches Perfectly
echo ./aaa-08-29 -- Matches Perfectly
echo ./aaa-08-31 -- Matches Perfectly
echo ./aaa-08-32 -- Matches Perfectly
echo ./aaa-09-01 -- Matches Perfectly
echo ./aaa-09-02B -- Matches Perfectly
echo ./aaa-09-02C -- Matches Perfectly
echo ./aaa-09-02 -- Matches Perfectly
echo ./aaa-09-03 -- Matches Perfectly
echo ./aaa-09-04 -- Matches Perfectly
echo ./aaa-09-05 -- Matches Perfectly
echo ./aaa-09-06 -- Matches Perfectly
echo ./aaa-09-07 -- Matches Perfectly
echo ./aaa-10-01 -- Matches Perfectly
echo ./aaa-10-02 -- Matches Perfectly
echo ./aaa-10-04 -- Matches Perfectly
echo ./aaa-11-01B -- Matches Perfectly
echo ./aaa-11-01 -- Matches Perfectly
echo ./aaa-11-03 -- Matches Perfectly
echo ./aaa-11-04 -- Matches Perfectly
echo ./aaa-11-06 -- Matches Perfectly
echo ./aaa-13-02 -- Matches Perfectly
echo ./aaa-13-03 -- Matches Perfectly
echo ./aaa-13-04 -- Matches Perfectly
echo ./aborthook -- Matches Perfectly
echo ./addtab -- Matches Perfectly
echo ./alias -- Matches Perfectly
echo ./andor14 -- Matches Perfectly
echo ./andor1 -- Matches Perfectly
echo ./andor2 -- Matches Perfectly
echo ./andor3 -- Matches Perfectly
echo ./andor4 -- Matches Perfectly
echo ./andor5 -- Matches Perfectly
echo ./anyorder -- Matches Perfectly
echo ./append -- Matches Perfectly
echo ./apply -- Matches Perfectly
echo ./arith1 -- Matches Perfectly
echo ./arith2 -- Matches Perfectly
echo ./arith3 -- Matches Perfectly
echo ./arith4 -- Matches Perfectly
echo ./arith5 -- Matches Perfectly
echo ./arith6 -- Matches Perfectly
echo ./arith7 -- Matches Perfectly
echo ./arith8 -- Matches Perfectly
echo ./arith9 -- Matches Perfectly
echo ./arnaud_bug -- Matches Perfectly
echo ./assert1 -- Matches Perfectly
echo ./assert2 -- Matches Perfectly
echo ./assert3 -- Matches Perfectly
echo ./assert4 -- Matches Perfectly
echo ./babcode -- Matches Perfectly
echo ./babel -- Matches Perfectly
echo ./bagof1 -- Matches Perfectly
echo ./bagof2 -- Matches Perfectly
echo ./bagof3 -- Matches Perfectly
echo ./bagof4 -- Matches Perfectly
echo ./bagof5 -- Matches Perfectly
echo ./bagof6 -- Matches Perfectly
echo ./bigstr -- Matches Perfectly
echo ./bitnot -- Matches Perfectly
echo ./bk_assign -- Matches Perfectly
echo ./boites1 -- Matches Perfectly
echo ./boites2 -- Matches Perfectly
echo ./boolpred2 -- Matches Perfectly
echo ./boolpred -- Matches Perfectly
echo ./brunobug -- Matches Perfectly
echo ./bruno_disj -- Matches Perfectly
echo ./call1 -- Matches Perfectly
./work.sh canonical
echo ./caret -- Matches Perfectly
echo ./cb -- Matches Perfectly
echo ./chapla -- Matches Perfectly
echo ./charcode -- Matches Perfectly
echo ./chart_parser1 -- Matches Perfectly
echo ./chart_parser2 -- Matches Perfectly
echo ./children -- Matches Perfectly
echo ./choice -- Matches Perfectly
echo ./clause -- Matches Perfectly
echo ./compose2 -- Matches Perfectly
echo ./compose -- Matches Perfectly
echo ./comp_struct -- Matches Perfectly
./work.sh condpred
echo ./constr -- Matches Perfectly
echo ./copy1 -- Matches Perfectly
echo ./copy2 -- Matches Perfectly
echo ./copy3 -- Matches Perfectly
echo ./copyfile -- Matches Perfectly
echo ./curry14 -- Matches Perfectly
echo ./curry15 -- Matches Perfectly
echo ./curry1 -- Matches Perfectly
echo ./curry2 -- Matches Perfectly
echo ./curry3 -- Matches Perfectly
echo ./curry4 -- Matches Perfectly
echo ./curry5 -- Matches Perfectly
echo ./curry6 -- Matches Perfectly
echo ./curry7 -- Matches Perfectly
echo ./curry8 -- Matches Perfectly
echo ./cut2 -- Matches Perfectly
echo ./cut3 -- Matches Perfectly
echo ./cycles1 -- Matches Perfectly
echo ./cycles2 -- Matches Perfectly
echo ./decl -- Matches Perfectly
echo ./delay2 -- Matches Perfectly
echo ./delay -- Matches Perfectly
echo ./dichotomy -- Matches Perfectly
echo ./dict -- Matches Perfectly
echo ./disequality1 -- Matches Perfectly
echo ./disequality2 -- Matches Perfectly
echo ./disequality3 -- Matches Perfectly
echo ./disequality4 -- Matches Perfectly
echo ./disequality5 -- Matches Perfectly
echo ./disequality6 -- Matches Perfectly
echo ./disequality7 -- Matches Perfectly
echo ./disequality8 -- Matches Perfectly
echo ./disequality9 -- Matches Perfectly
echo ./disj1 -- Matches Perfectly
echo ./disj2 -- Matches Perfectly
echo ./disj3 -- Matches Perfectly
echo ./disj4 -- Matches Perfectly
echo ./disj5 -- Matches Perfectly
echo ./disj6 -- Matches Perfectly
echo ./disj7 -- Matches Perfectly
echo ./dissolve -- Matches Perfectly
echo ./dupfeat -- Matches Perfectly
echo ./dynstat -- Matches Perfectly
echo ./encapsulate -- Matches Perfectly
echo ./eoftest2 -- Matches Perfectly
echo ./eoftest3 -- Matches Perfectly
echo ./eoftest -- Matches Perfectly
echo ./eratosthenes -- Matches Perfectly
echo ./errordecl -- Matches Perfectly
echo ./example -- Matches Perfectly
echo ./extest -- Matches Perfectly
echo ./fact -- Matches Perfectly
echo ./factorize -- Matches Perfectly
echo ./fail -- Matches Perfectly
echo ./featnames -- Matches Perfectly
echo ./feat_order -- Matches Perfectly
echo ./feature -- Matches Perfectly
echo ./feature_module -- Matches Perfectly
echo ./features1 -- Matches Perfectly
echo ./featval -- Matches Perfectly
echo ./foo -- Matches Perfectly
echo ./funcself -- Matches Perfectly
echo ./function2 -- Matches Perfectly
echo ./fusil -- Matches Perfectly
echo ./gauss -- Matches Perfectly
echo ./gctest -- Matches Perfectly
echo ./genint -- Matches Perfectly
echo ./glb -- Matches Perfectly
echo ./glblub -- Matches Perfectly
echo ./global2 -- Matches Perfectly
echo ./global3 -- Matches Perfectly
echo ./global -- Matches Perfectly
echo ./glob_gc -- Matches Perfectly
echo ./glob_test2 -- Matches Perfectly
echo ./grammars -- Matches Perfectly
echo ./hamming -- Matches Perfectly
echo ./hanoi -- Matches Perfectly
echo ./hasfeature -- Matches Perfectly
echo ./inherit -- Matches Perfectly
echo ./intabs -- Matches Perfectly
echo ./intdiv2 -- Matches Perfectly
echo ./intdiv3 -- Matches Perfectly
echo ./intdiv -- Matches Perfectly
echo ./intlist -- Matches Perfectly
echo ./inttrace -- Matches Perfectly
echo ./isatest2 -- Matches Perfectly
echo ./isatest -- Matches Perfectly
echo ./junk -- Matches Perfectly
echo ./lazyinherit -- Matches Perfectly
echo ./lazy -- Matches Perfectly
echo ./lefun1 -- Matches Perfectly
echo ./lefun2 -- Matches Perfectly
echo ./libstruct -- Matches Perfectly
echo ./list_bda -- Matches Perfectly
echo ./listing1 -- Matches Perfectly
echo ./listing2 -- Matches Perfectly
echo ./loadquery -- Matches Perfectly
echo ./longstr -- Matches Perfectly
echo ./lub -- Matches Perfectly
echo ./machine -- Matches Perfectly
echo ./magic -- Matches Perfectly
echo ./makestr -- Matches Perfectly
echo ./manual10 -- Matches Perfectly
echo ./manual11 -- Matches Perfectly
echo ./manual1 -- Matches Perfectly
echo ./manual2 -- Matches Perfectly
echo ./manual3 -- Matches Perfectly
echo ./manual4 -- Matches Perfectly
echo ./manual5 -- Matches Perfectly
echo ./manual6 -- Matches Perfectly
echo ./manual7 -- Matches Perfectly
echo ./manual8 -- Matches Perfectly
echo ./manual9 -- Matches Perfectly
echo ./many_types -- Matches Perfectly
echo ./module_test1a -- Matches Perfectly
echo ./module_test1 -- Matches Perfectly
echo ./module_test2 -- Matches Perfectly
./work.sh module_test3
echo ./module_test4 -- Matches Perfectly
echo ./module_test5 -- Matches Perfectly
echo ./module_test6 -- Matches Perfectly
echo ./mort -- Matches Perfectly
echo ./mresid -- Matches Perfectly
echo ./n2 -- Matches Perfectly
echo ./naming -- Matches Perfectly
echo ./nesting -- Matches Perfectly
echo ./nicetest -- Matches Perfectly
echo ./nl -- Matches Perfectly
echo ./nofour -- Matches Perfectly
echo ./nonstrict1 -- Matches Perfectly
echo ./nonstrict2 -- Matches Perfectly
echo ./nonstrict3 -- Matches Perfectly
echo ./nonstrict4 -- Matches Perfectly
echo ./nonstrict5 -- Matches Perfectly
echo ./nonvar -- Matches Perfectly
echo ./not -- Matches Perfectly
echo ./numeric -- Matches Perfectly
echo ./op1 -- Matches Perfectly
echo ./op2 -- Matches Perfectly
echo ./op3 -- Matches Perfectly
echo ./order -- Matches Perfectly
echo ./overload -- Matches Perfectly
echo ./pagewidth -- Matches Perfectly
echo ./parents -- Matches Perfectly
echo ./parse2 -- Matches Perfectly
echo ./parse -- Matches Perfectly
echo ./parser -- Matches Perfectly
echo ./part -- Matches Perfectly
echo ./peep -- Matches Perfectly
echo ./pers2 -- Matches Perfectly
echo ./persistent2 -- Matches Perfectly
echo ./persistent -- Matches Perfectly
echo ./person1 -- Matches Perfectly
echo ./person2 -- Matches Perfectly
echo ./posint -- Matches Perfectly
echo ./power -- Matches Perfectly
echo ./preparser -- Matches Perfectly
echo ./prime -- Matches Perfectly
echo ./print1 -- Matches Perfectly
echo ./print2 -- Matches Perfectly
echo ./print_depth1 -- Matches Perfectly
echo ./print_depth2 -- Matches Perfectly
echo ./print_test -- Matches Perfectly
echo ./printvar -- Matches Perfectly
echo ./profiler1 -- Matches Perfectly
echo ./profiler2 -- Matches Perfectly
echo ./profiler3 -- Matches Perfectly
echo ./project1 -- Matches Perfectly
echo ./project2 -- Matches Perfectly
echo ./project3 -- Matches Perfectly
echo ./prove -- Matches Perfectly
echo ./psi2str -- Matches Perfectly
echo ./puke -- Matches Perfectly
echo ./put_get -- Matches Perfectly
echo ./pyth2 -- Matches Perfectly
echo ./pyth -- Matches Perfectly
echo ./qsort1 -- Matches Perfectly
echo ./qsort2 -- Matches Perfectly
echo ./query_decl -- Matches Perfectly
echo ./random -- Matches Perfectly
echo ./resid1 -- Matches Perfectly
echo ./resid2 -- Matches Perfectly
echo ./retract1 -- Matches Perfectly
echo ./retract2 -- Matches Perfectly
echo ./retract3 -- Matches Perfectly
echo ./retract4 -- Matches Perfectly
echo ./retract5 -- Matches Perfectly
echo ./retract6 -- Matches Perfectly
echo ./retract7 -- Matches Perfectly
echo ./rootsort2 -- Matches Perfectly
echo ./rootsort -- Matches Perfectly
echo ./schedule1 -- Matches Perfectly
echo ./schedule2 -- Matches Perfectly
echo ./school -- Matches Perfectly
echo ./self -- Matches Perfectly
echo ./share -- Matches Perfectly
echo ./simp_eqn -- Matches Perfectly
echo ./smalltwente -- Matches Perfectly
echo ./smm -- Matches Perfectly
echo ./soap -- Matches Perfectly
echo ./sortcycle1 -- Matches Perfectly
echo ./sortcycle2 -- Matches Perfectly
echo ./sortcycle3 -- Matches Perfectly
echo ./sortcycle4 -- Matches Perfectly
echo ./sortcycle5 -- Matches Perfectly
echo ./str2psi -- Matches Perfectly
echo ./strbug -- Matches Perfectly
echo ./streams -- Matches Perfectly
echo ./strip -- Matches Perfectly
echo ./str -- Matches Perfectly
echo ./sub -- Matches Perfectly
echo ./subs -- Matches Perfectly
echo ./subsort -- Matches Perfectly
echo ./t3201 -- Matches Perfectly
echo ./t3202 -- Matches Perfectly
echo ./t3203 -- Matches Perfectly
echo ./t3204 -- Matches Perfectly
echo ./t3205 -- Matches Perfectly
echo ./t3206 -- Matches Perfectly
echo ./t3207 -- Matches Perfectly
echo ./t4105 -- Matches Perfectly
echo ./t4202 -- Matches Perfectly
echo ./t4502 -- Matches Perfectly
echo ./t4505 -- Matches Perfectly
echo ./t8101 -- Matches Perfectly
echo ./t8102 -- Matches Perfectly
echo ./t8103 -- Matches Perfectly
echo ./t8104 -- Matches Perfectly
echo ./t8105 -- Matches Perfectly
echo ./tan -- Matches Perfectly
echo ./termsize -- Matches Perfectly
echo ./test00 -- Matches Perfectly
echo ./test04 -- Matches Perfectly
echo ./testprof -- Matches Perfectly
echo ./testslc -- Matches Perfectly
echo ./testsl -- Matches Perfectly
echo ./titi -- Matches Perfectly
echo ./t -- Matches Perfectly
echo ./tri_ins -- Matches Perfectly
echo ./tripeq -- Matches Perfectly
echo ./two_bugs -- Matches Perfectly
echo ./typedisj -- Matches Perfectly
echo ./unary -- Matches Perfectly
echo ./unify -- Matches Perfectly
echo ./varlevel2 -- Matches Perfectly
echo ./varlevel -- Matches Perfectly
echo ./volanski1 -- Matches Perfectly
echo ./wambruno -- Matches Perfectly
echo ./wam -- Matches Perfectly
echo ./wlife -- Matches Perfectly
echo ./write -- Matches Perfectly
echo ./writeq -- Matches Perfectly
echo ./xor -- Matches Perfectly
echo ./z_comb -- Matches Perfectly
echo ./z_cut2 -- Matches Perfectly
echo ./z_gcsimp -- Matches Perfectly
echo ./z_gctoken2 -- Matches Perfectly
echo ./z_maurice -- Matches Perfectly
echo ./z_power_4 -- Matches Perfectly
echo ./z_pyth_gc -- Matches Perfectly
echo 407 Total Tests completed
echo 404 Total Tests match
echo 3 Total Tests differ
echo 3 Total Tests out differ
echo 1 Total Tests err differ
