#!/bin/csh

set DIRECTORY = `pwd`

setenv SLDIR /udir/venet/LIFE/SUPERLINT/PACKAGE


chdir $SLDIR

~/bin/wild_life_X -q $DIRECTORY sl.lf $* <<EOF

[@, "-q", Directory, Binary | Args] = argv,
  load(Binary),
    wl_main(Directory, Args),
      halt ?
EOF
